### ISSUE TITLE
Missing Keybinds when updating from Botania-1.16.2-406 to Botania-1.16.3-408 MC 1.16.3

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Botania#3487] opened 2020-10-18 23:42 UTC
# Version Information
Forge version: forge-34.1.23
Botania version: Botania-1.16.3-408

# Further Information
All I did was update from Botania-1.16.2-406 to Botania-1.16.2-407 and the corporea keybinding is missing. If you enter inventory and browse JEI and press esc it crashes.

What I expected to happen:

No crash. Also keybinding to exist.

What happened instead:

[crash-2020-10-18_18.41.56-client.txt](https://github.com/Vazkii/Botania/files/5398378/crash-2020-10-18_18.41.56-client.txt)

[latest.log](https://github.com/Vazkii/Botania/files/5398379/latest.log)

**Comment by Hubry** [comment] 2020-10-19 10:44
Duplicate of #3483 (which is your issue, why are you posting again?). fixed in 7cd0c3938a7c5ad423dc21eec82333b510991409 (as you can see in the close message on your issue), wait for a new build.

**Closed by Hubry** 2020-10-19 10:44 UTC
