### ISSUE TITLE
Hitboxes do not line up with flowers

### ISSUE THREAD

**Issue by PapiDimmi** [Vazkii/Botania#2242] opened 2017-04-10 15:35 UTC
@Vazkii decided to make each functional flower appear in different spaces on a block rather than centering them—probably for some realistic variety—and that’s fine and all, but the hitboxes do not line up with the flowers, which is extremely annoying when trying to break flowers, using the manaseer monocle, or using the wand of the forest.

This has been posted before (#2172), but it was closed, even though the issue has not been fixed. Apparently, as @williewillus mentioned, this bug has been fixed in the 1.11.2 version of Botania (which I cannot verify), but lots of people still use 1.10.2, and its modding community is much larger; therefore, it would be fantastic if this were fixed for the 1.10.2 version, too!

By the way, I also use OptiFine; I’m unsure whether that’s what’s causing the issue like it was mentioned in #2172.

## Screenshot
![2017-04-10_17 37 27](https://cloud.githubusercontent.com/assets/25916106/24869723/71cd87e6-1e14-11e7-8bf6-e9539bf33342.png)

## Versions
**Minecraft version**: 1.10.2
**Botania version**: r1.9-341
**OptiFine version**: HD U D7
**Forge version**: 12.18.3.2272

**Comment by Luxor5393** [comment] 2017-04-10 18:49
As williewillus said in the original report this is a vanilla bug fixed in 1.11

**Comment by PapiDimmi** [comment] 2017-04-10 18:51
Quoting myself here:

>This has been posted before (#2172), but it was closed, even though the issue has not been fixed. Apparently, as @williewillus mentioned, this bug has been fixed in the 1.11.2 version of Botania (which I cannot verify), but lots of people still use 1.10.2, and its modding community is much larger; therefore, it would be fantastic if this were fixed for the 1.10.2 version, too!

Why did @Vazkii only fix this in the 1.11.2 version? Lots of people still use the 1.10.2 version.

**Comment by williewillus** [comment] 2017-04-10 19:44
this isn't gamebreaking and at the moment making releases for previous mc versions breaks the build number ordering

**Comment by PapiDimmi** [comment] 2017-04-10 19:45
Eh, all right. Well, I hope that this will be fixed in the future, as it’s pretty annoying.

**Comment by Luxor5393** [comment] 2017-04-11 12:20
> Why did @Vazkii only fix this in the 1.11.2 version? Lots of people still use the 1.10.2 version.

Again this is **vanilla bug** therefore it was fixed by mojang in 1.11, not vazkii. From the wiki:
 *Flowers: Their hitbox now corresponds to their exact visual location on the block (as opposed to always placed in the middle of the block).

http://minecraft.gamepedia.com/1.11#Blocks_2

**Comment by williewillus** [comment] 2017-04-11 12:28
It also needs some fixing on my end which needs a forge fix to fully take effect. Keeping this open till then

**Comment by PapiDimmi** [comment] 2017-04-11 12:37
@Luxor5393 Oh, I didn’t know. My bad.

**Comment by williewillus** [comment] 2017-05-03 19:28
Should be fixed in forge 2292 and up

**Closed by williewillus** 2017-05-03 19:28 UTC

**Comment by PapiDimmi** [comment] 2017-05-03 19:30
@williewillus
Firstly, I thought that this was a vanilla bug; why would Forge fix a Minecraft bug?
Secondly, 2292 is for 1.11, and it was fixed in 1.11, so why would Forge fix a bug that’s already fixed?

I want this annoying bug fixed in 1.10.

**Comment by PapiDimmi** [comment] 2017-05-03 19:30
@williewillus
Firstly, I thought that this was a vanilla bug; why would Forge fix a Minecraft bug?
Secondly, 2292 is for 1.11, and it was fixed in 1.11, so why would Forge fix a bug that’s already fixed?

I want this annoying bug fixed in 1.10.2.

**Comment by williewillus** [comment] 2017-05-03 19:40
this isn't caused by one bug, it's caused by a vanilla bug and a forge bug together. Forge one only got fixed in 2292.

**Comment by PapiDimmi** [comment] 2017-05-03 19:48
It’s incredibly annoying, though. It shouldn’t be high priority, but I wish they’d still fix it.
