### ISSUE TITLE
Crash when rendering pylons

### ISSUE THREAD

**Issue by BenjaminLeSire** [Vazkii/Botania#3680] opened 2021-03-09 14:01 UTC
# Version Information
Forge version:  36.0.46
Botania version:  1.16.4-413 (also tested with all the versions down to 1.16.4-410)
Curios version:  1.16.5-4.0.5.0
Patchouli version:  1.16.4-50

# Further Information
Link to crash log: https://gist.github.com/BenjaminLeSire/9c9432a1b7ba5ef6cf2e2589e4368e7f
Steps to reproduce:
1. Create a world and either do a lot of botania stuff, either go to creative
2. if in creative, scroll down the botania item list until the game crashes; you can trigger the same crash with an unlocked enough book, and scrolling down the index page.

What I expected to happen: not crashing the game

What happened instead: crashed the game

**Comment by Hubry** [comment] 2021-03-09 23:23
> Java VM Version: Eclipse OpenJ9 VM 
Duplicate of #3647, use HotSpot. The game isn't even supposed to launch on this JVM but Modlauncher's detection is broken.

**Closed by Hubry** 2021-03-09 23:23 UTC
