### ISSUE TITLE
Looms do not display the default banner patterns with Botania installed.

### ISSUE THREAD

**Issue by Scironex** [Vazkii/Botania#4296] opened 2023-02-17 14:27 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

Forge: 43.2.3

### The latest.log file

https://pastebin.com/Q71XW0FY

### Issue description

The default banner patterns are not available in the Loom block whilst Botania is installed. This makes it impossible to create most patterned banners in normal gameplay.

### Steps to reproduce

1. Place a Loom Block
2. Open the Loom's interface and place a banner and dye item in their respective slots.

### Other information

Banner patterns that require a pattern item - such as the Flower Charge Banner Pattern - work without issue if the pattern item is supplied.

Naturally generated patterned banners, such as the Ominous Banner and the banners in End Cities, function normally. I have not tested whether banners with patterns can be created with commands, but combined with the previous observation, my impression is that this is an issue more with the Loom block than it is with the banners.

The issue was originally discovered with other mods installed, but I've tested a fresh installation with no mods other than Botania and its required dependencies, and the issue is still present. Despite not being a listed dependency, I have also tested this with and without AutoRegLib - which is usually a requirement for mods originally authored by Vazkii - and it's present regardless.

I have not tested this with all dye items, but I have confirmed that it is present with white, red, yellow and green dyes.

**Comment by LeoBeliik** [comment] 2023-02-17 15:59
https://github.com/VazkiiMods/Botania/issues/4253

**Comment by williewillus** [comment] 2023-04-03 16:49
Duplicate of #4253 which has been fixed

**Closed as not planned by williewillus** 2023-04-03 16:49 UTC
