### ISSUE TITLE
Text are all boxes~

### ISSUE THREAD

**Issue by IceCubedBear** [Vazkii/Botania#3252] opened 2020-04-17 02:44 UTC
[
# Version Information
Forge version:  1.15.2-31.1.46
Botania version: Botania +r1.15-382

What I expected to happen: The usual you can read text 

What happened instead: https://cdn.discordapp.com/attachments/681153953521860700/700536195461152768/2020-04-17_11.33.23.png

**Comment by Alwinfy** [comment] 2020-04-18 01:15
Dupe of #3216?

**Comment by wizd3m** [comment] 2020-04-18 06:47
Please do not close this issue. #3216 points to a round-robin of closed issues. I experience this issue too on 1.14.4.

**Comment by Hubry** [comment] 2020-04-18 15:01
> points to a round-robin of closed issues

It only points to the actual issue, Vazkii/Patchouli#197, which is already fixed in Patchouli 1.2-29 for 1.15.2. Sadly bugfix backports for Vazkii's mods are very rare, you'll have a better chance to get one if you bug Williewillus in Vazkii's discord. This is not a Botania issue anyways, so closing.

**Closed by Hubry** 2020-04-18 15:01 UTC

**Comment by williewillus** [comment] 2020-04-19 07:26
Released a patchouli 1.14 hotfix for this btw.
