### ISSUE TITLE
if I plant petals in dirt he not drop's

### ISSUE THREAD

**Issue by DyeffersonAz** [Vazkii/Botania#1773] opened 2016-01-23 18:47 UTC
//

**Comment by yrsegal** [comment] 2016-01-23 18:48
[/r/titlegore](reddit.com/r/titlegore)

Can you explain the issue further?

**Comment by DyeffersonAz** [comment] 2016-01-23 18:51
I break a high flower and not drop...

**Comment by yrsegal** [comment] 2016-01-23 18:51
have you tried shears?

**Comment by DyeffersonAz** [comment] 2016-01-23 18:58
no, thanks!

**Comment by yrsegal** [comment] 2016-01-23 18:58
please close the issue, as this is intended behavior. And read the Lexica Botania next time.

**Closed** 2016-01-23 19:07 UTC
