### ISSUE TITLE
Not compatible with Enhanced-Celestials

### ISSUE THREAD

**Issue by silentnyte** [Vazkii/Botania#3900] opened 2022-01-12 01:13 UTC
### Mod loader

Fabric

### Minecraft version

1.17.1

### Botania version

1.17.1-422

### Modloader version

Fabric 0.12.12

### The latest.log file

https://paste.ee/p/SvYLW

### Issue description

Minecraft with not launch with Botania and Enhanced-Celestials

**Comment by silentnyte** [comment] 2022-01-12 01:14
https://github.com/CorgiTaco/Enhanced-Celestials/issues/95

**Comment by Hubry** [comment] 2022-01-12 01:15
Duplicate of #3873, this is already fixed on 1.18, how useful is it to actually go back to backport this?

**Comment by silentnyte** [comment] 2022-01-12 12:27
> Duplicate of #3873, this is already fixed on 1.18, how useful is it to actually go back to backport this?

It is only useful until Yung and Charm are updated to 1.18.

**Closed as completed** 2022-03-22 00:34 UTC
