### ISSUE TITLE
Floating Endoflame turns "floating Botania flower" in Iron Backpacks

### ISSUE THREAD

**Issue by FeinEmber** [Vazkii/Botania#2398] opened 2017-10-01 21:13 UTC
Minecraft ver. 1.10.2
Forge ver. 12.18.3.2316
Botania ver. r1.9-341
Iron Backpacks ver. 2.2.27

Stored four floating endoflames in a diamond level, "storage emphasis" Iron Backpack when I logged off, came back to "floating Botania flower". Even got an achievement when I put it down, then picked it back up. Flower looks like a red poppy. Could possibly be a Halloween-themed bug. Also, somehow one that's been placed and picked up is different enough from the originally found "floating Botania flower" to not stack with it. So far, not repeatable, so maybe not real help.

Edit:
Also noticed that a few times, when I break a floating flower, for an instant before it gets picked up, it also turns into "floating Botania flower", at least until it shows in inventory.

**Comment by williewillus** [comment] 2017-10-01 22:30
iron backpacks somehow lost the NBT tags on the flower

**Comment by williewillus** [comment] 2017-10-19 13:35
^ not really sure what else there is to it if you can't reproduce it though. The flower type is just a normal NBT tag like enchantments so I highly doubt it's a botania bug, closing as such

As for the flickering, that's just lag between clientside and serverside, the client deletes the block, the server says "no it's still there", then finally the server deletes it too.

**Closed by williewillus** 2017-10-19 13:35 UTC
