### ISSUE TITLE
Crash when rendering a mana poolv

### ISSUE THREAD

**Issue by Chefbarbie** [Vazkii/Botania#2422] opened 2017-10-22 18:16 UTC
https://pastebin.com/Guuus4Nk

Happens once. Then good. Removing the mana pool removes the crash.

**Comment by katabame** [comment] 2017-10-22 18:50
https://gist.github.com/katabame/10e80d2fe4caba47fea79b8f26af6045
Same here, on multiplay server using `Botania r1.10-349` with `forge 1.12.2 - 14.23.0.2515`.
Crash occurred when you're near of manapool. 
 `Block location: World: (1279,70,1023)` (L52) This position looks like random position in every each crashs/users.

**Comment by Akai1** [comment] 2017-10-22 19:54
Same as #2338.

**Comment by williewillus** [comment] 2017-10-22 23:20
Is this on a sponge server?
and yes duplicate of #2205 so closing, but I'm curious if it's a sponge server or not.

One of these days I'll go and replace all of these to guard against the sponge weirdness

**Closed by williewillus** 2017-10-22 23:20 UTC

**Comment by katabame** [comment] 2017-10-23 07:02
@williewillus In my crash case, server is not sponge server. It's just forge server that installed with forge installer.
