### ISSUE TITLE
Lexica entry: Runic Altar pages 1 and 7 are the same.

### ISSUE THREAD

**Issue by OJwithC** [Vazkii/Botania#1255] opened 2015-08-15 00:51 UTC
Botania v208

Page one of the runic altar's entry seems to be a copy of page 7. ("Similar to the Petal Apothecary, right clicking..." etc.)

**Comment by MrKunji** [comment] 2015-08-15 00:52
Duplicate of https://github.com/Vazkii/Botania/issues/1244
@TheWhiteWolves fixed it already

**Closed** 2015-08-15 05:02 UTC

**Comment by OJwithC** [comment] 2015-08-15 05:06
That's what I get for going off of memory instead of double-checking closed issues. Whoops!
