### ISSUE TITLE
Quests requiring killing

### ISSUE THREAD

**Issue by Gnera666** [Vazkii/Botania#2813] opened 2018-12-30 03:28 UTC
# Version Information
Forge version:  14.23.4.2705
Botania version:  Garden of Glass (Questbook Edition)3.6

The quests that require you to kill a specific mob (the quest 'Gaia' - second page wants you to kill Gaia, or the quest 'Animals' - second to sixth page wants you to kill chicken, cow, villager, sheep and ocelot) are not updating/ advancing.

I haven't installed any other additional mods or altered any existing (don't know if this information is needed or not but might as well put it here).

For the record I have killed Gaia (normal mode) 3 times, gotten the head and music disk to drop, and the Gaia 2.0 3 times but the quest for killing the normal mode Gaia hasn't updated, same with the Animals quest where I've killed probably 50+ chickens, cows, sheep and even a villager (it was a turned zombie villager), granted I've yet to kill an ocelot, however none of these quests are updating.

**Comment by williewillus** [comment] 2018-12-31 05:36
botania doesn't have any built-in auto-updating quests beyond the advancements. the challenges in the lexicon are manually marked as complete by the player.

I think the problem is the quest-tracking mod in the modpack, not Botania itself

**Comment by Gnera666** [comment] 2018-12-31 09:31
Oh, OK, then I know.
Thanks.

**Closed as completed** 2018-12-31 20:29 UTC
