### ISSUE TITLE
Abstruse Platform disguised for one player and not others

### ISSUE THREAD

**Issue by mattwandcow** [Vazkii/Botania#4377] opened 2023-05-23 22:33 UTC
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Botania version

1.19.2-438-FABRIC

### Modloader version

Fabric-loader-0.14.19-1.19.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/wickedwitches-smp

### The latest.log file

n/a

### Issue description

A player on our server was attempting to make a secret door using abstruse platforms, but to them, it did not appear to change when the block had a disguise applied. To me, it appears to function normally. A second player confirms that they also do not see the block's disguise.

It also doesn't function in that player's single player world.

**Comment by williewillus** [comment] 2023-05-29 00:06
I can't reproduce this with just botania

**Comment by FizzBuzz3000** [comment] 2023-05-29 02:46
What extra mods did this person have? perhaps there's some conflict occurring between some mods.

**Comment by mattwandcow** [comment] 2023-05-29 04:11
They claim to have nothing more than what's in the pack. Admittedly, the pack has 132 mods, so some conflict is certainly possible. 

Here's a current list of the mods in the pack.
[witches mod list.txt](https://github.com/VazkiiMods/Botania/files/11588340/witches.mod.list.txt)

**Comment by anoomolu** [comment] 2024-01-13 11:24
I know this is pretty late, but Sodium doesn't play nice with Abstruse Platform disguising (read as doesn't work, at least on 1.19.2 and 1.20.1). Maybe they added that on their own?

**Comment by TheRealWormbo** [comment] 2024-05-03 21:02
Sodium-compatibility is likely fixed in the latest dev snapshot, pending release eventually. Remember that you also need Indium if you want to use (pre-0.6) Sodium with mods.

**Comment by TheRealWormbo** [comment] 2024-07-13 07:42
Closing this since 1.19 won't receive updates anymore, and this doesn't seem reproducible.

**Closed as not planned by TheRealWormbo** 2024-07-13 07:42 UTC
Labels: compatibility, cant-reproduce
