### ISSUE TITLE
[1.16.1] Hourglass Item Render Crash

### ISSUE THREAD

**Issue by LittleMissAlissa** [Vazkii/Botania#3391] opened 2020-08-10 20:53 UTC
# Version Information
Forge version:  1.16 - 32.0.108
Botania version:  1.16-399

# Further Information
Link to crash log: https://pastebin.com/6pPeEm3v

Steps to reproduce:
1. Search for Hourglass in Item list in Creative Mode
2. Alternatively opening the book

What I expected to happen: Book to open / Hourglass to appear in item list

What happened instead: Crash to Desktop

**We have linked the issue with Optifine version " OptiFine 1.16.1 HD U G2 "**

**Comment by Hubry** [comment] 2020-08-10 22:41
Duplicate of #3387, remove optifine or downgrade forge to build 106

**Closed by Hubry** 2020-08-10 22:41 UTC
