### ISSUE TITLE
Botania crash with Thaumcraft

### ISSUE THREAD

**Issue by DevTimur** [Vazkii/Botania#2612] opened 2018-04-24 12:55 UTC
# Version Information
Forge version:  14.23.3.2673
Botania version:  Botania+r1.10-353
Compatibility issue mod: Thaumcraft-1.12.2-6.1.BETA10

# Further Information
Link to crash log: https://gist.github.com/DevTimur/a265eb28ce8ed6d70722c19ca7c67339
Steps to reproduce:
1. Add Thaumcraft mod
2. Lauch game
3. Crash
What I expected to happen:
I expected modpack to work :)
What happened instead:
Thaumcraft killed Botania, Azanor claim it's Botania's fault

**Comment by NillerMedDild** [comment] 2018-04-24 12:56
Duplicate of #2608

**Comment by DevTimur** [comment] 2018-04-24 12:57
Yeah, but it's 1.12.2 version

**Comment by CurePindal** [comment] 2018-04-24 12:58
Its still a duplicate, because its from an outdated API reference.

**Comment by kasper-tfg** [comment] 2018-04-24 13:32
Even with Botania 354 it s still crashing.  
https://paste.ee/p/CpLR0

**Comment by CurePindal** [comment] 2018-04-24 14:35
So the commit that should be a hotfix isnt a fix? Derp.

**Closed** 2018-04-24 15:25 UTC
