### ISSUE TITLE
Can't break blocks using Manasteel Tools with a Band of Mana on a Bauble slot

### ISSUE THREAD

**Issue by giorigor** [Vazkii/Botania#2514] opened 2018-01-13 03:36 UTC
**Minecraft version:** 1.12.2
**Forge version:** 14.23.1.2587
**Botania version:** r1.10-352
**Link to crash log:** [not a crash per se, more of an error](https://gist.github.com/giorigor/822da3a0d38120322c884200fe2b1300)
[other mods](https://imgur.com/efRKrAI)

**Steps to reproduce:**
1. Start Singleplayer.
2. Get a Manasteel Tool (eg. Manasteel Axe).
3. Get a Band of Mana and fill it up on a Pool.
4. Put the Band at a Bauble ring slot.
5. Try to break a block (eg. a Tree, or Livingwood).

**What I expected to happen:**
* The block breaks and its "item version" drops on the ground.

**What happened instead:**
* The block becomes invisible, doesn't drop anything. Kinda like desync. It still exists, has some weird colision, and block updates make it reappear. No mana is lost.
* If the Band is removed from the Bauble slot, and put in a "normal" inventory slot, the tool can be used normally (not sure if that's a feature, since there's a [issue report](https://github.com/Vazkii/Botania/issues/2478) on this).

**Observations:**
* All mods updated, etc etc etc, I followed the guidelines.
* Tried disabling Optifine, no such luck.
* Tried on a new world, still can't break stuff.
* Didn't test every single Manasteel tool. Pickaxe, Axe and Shears confirmed.
* It's probably related to Baubles, but not sure if it is their fault.

**Comment by williewillus** [comment] 2018-01-13 04:27
same root cause as #2509 (downgrade baubles to previous version or wait for the fix for this)

**Closed by williewillus** 2018-01-13 04:27 UTC
