### ISSUE TITLE
Mana bar doesn't update with terra truncator

### ISSUE THREAD

**Issue by ray10k** [Vazkii/Botania#1179] opened 2015-07-17 21:14 UTC
While chopping down a wood farm with the truncator, I noticed it was taking damage, despite my experience bar claiming I had about 3/4 mana left. Checking the baubles tab, my mana ring was completely depleted.
Taking the ring out of its slot and putting it back in did update the bar.

**Comment by Vazkii** [comment] 2015-07-18 18:23
Dupe of  #1083

**Closed by Vazkii** 2015-07-18 18:23 UTC
