### ISSUE TITLE
Rendering issues with Oculus and Shaders

### ISSUE THREAD

**Issue by Wraen** [Vazkii/Botania#4199] opened 2022-10-31 17:16 UTC
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

40.1.68

### Modpack info

Custom pack

### The latest.log file

https://gist.github.com/Wraen/477f3bebc5db651d433b2623e228e74f

### Issue description

Mana pools appear empty, pylons not rendering fully and sparks do not appear at all when shaders are turned on. I am using the version listed above, with rubidium, iris, create, and the iris/flywheel compat. I have looked through the issue logs for these other mods, and it seems that this issue has happened for other people, and lies with botania and not the others.

![2022-10-31_17 08 03](https://user-images.githubusercontent.com/63731507/199067175-b4371981-523e-4849-98d4-1ac9eb200da3.png)

### Steps to reproduce

1. install the mods listed in description including shaders.
2. place any of the affected blocks in game. 
3. You will see (or not see, as is the case with sparks) issues with the rendering.

**Comment by williewillus** [comment] 2022-11-01 01:42
Gonna just mark this as a duplicate of #3951 and track it there

**Closed as not planned by williewillus** 2022-11-01 01:42 UTC
