### ISSUE TITLE
Sparks with augment dont update the mana transport

### ISSUE THREAD

**Issue by Bellwar** [Vazkii/Botania#1160] opened 2015-07-11 12:23 UTC
I was leaving report for this and you told me you cant reproduce it and i found Direwolf20 to have this problem to in his video (https://youtu.be/SzdPE_oszXQ?t=30m21s) and YES it is still same in new versions on my clint.

**Comment by TheWhiteWolves** [comment] 2015-07-11 13:11
Had a look at this and it only happens to sparks that are on pylons, other sparks are generating particles fine.

**Comment by Bellwar** [comment] 2015-07-11 14:16
Well, i have tested it and same problem for everything that is on the top of the mana pool. So everytime the spark is moved up you got this problem.

**Comment by TheWhiteWolves** [comment] 2015-07-11 14:58
yep, from my further testing that seems to be the case, whenever the spark is moved upwards, whether this is done by a pylon or block (glass block) makes no difference, the second it moves the particles stop and once you remove the item that moved the spark it returns to normal.

This will require further investigation into the cause and I'll probably need to talk to vaz about how he deals with the moving of the spark as I can't find it atm.

**Comment by TheWhiteWolves** [comment] 2015-07-11 17:28
Looks like it's caused by a vanilla mechanic which shifts the spark out of the block it's in, for the moment I'm going to close this issue until a time when we can find a solution.

**Closed by TheWhiteWolves** 2015-07-11 17:28 UTC
Labels: bug, investigate, minor
