### ISSUE TITLE
[1.16-401] Crash when feeding endoflames/mana burst from spreader

### ISSUE THREAD

**Issue by Blackcatz1911** [Vazkii/Botania#3398] opened 2020-08-13 09:00 UTC
# Version Information
Forge version:  forge-1.16.1-32.0.107-universal
Botania version:  1.16-401

# Further Information
Link to crash log: https://pastebin.com/rQVF4UAw
Steps to reproduce:
1. Place Manapool
2. Place Manaspreader facing the pool (No manual bind)
3. Place endoflame next to Spreader (No manual bind)
4. Give them some coal.

What I expected to happen:
No crash.

What happened instead:
Crash. (Unsure when eating or when bursting into the pool)

Seems to be related to: https://github.com/Vazkii/Botania/issues/3397

**Comment by Hubry** [comment] 2020-08-13 10:02
Duplicate of #3397

**Closed by Hubry** 2020-08-13 10:02 UTC
