### ISSUE TITLE
Another Sash bug

### ISSUE THREAD

**Issue by bosto2** [Vazkii/Botania#1014] opened 2015-05-24 16:27 UTC
## Botania: r1.6-190

when having the sash on you can not pass thru a certain some stairs
Screenshot: http://prntscr.com/78ue4b

**Comment by MrKunji** [comment] 2015-05-24 16:30
Step assist work funny in stairs, also, your lighting isn't helping much, take the screenshot again with better light.

**Comment by bosto2** [comment] 2015-05-24 16:55
http://prntscr.com/78uoqy it occurs if you try and go thru stairs on the top and bottom

**Comment by MrKunji** [comment] 2015-05-24 17:14
I've experienced the same with the Free Runners (Mekanism), it's because the way step assist works, I don't know if something can be done about.

**Comment by TheWhiteWolves** [comment] 2015-05-24 18:59
Its a problem that exists with pretty much everything that gives step assist, boots of the traveller, sashes, Free Runners (as MrKunki said above) etc.

**Comment by Entoarox** [comment] 2015-05-25 00:56
This is an issue with collision detection in minecraft itself and not an issue in botania, it is the same reason you cannot walk into a 2 block high gap from soul sand.

**Comment by bosto2** [comment] 2015-05-25 08:28
While it might be a issue with Minecraft its not a issue "in Minecraft itself" since Minecraft does not modify the stephight witch I assume is the  issue and I can't think of a way of a way around it. Just wanted to note it incase of somebody knowing the solution

**Comment by TheWhiteWolves** [comment] 2015-05-25 09:27
Unfortunately it is a problem in minecraft itself, the way step height alteration works in mods is a simple case of changing player.stepHeight in vanilla minecraft from 0.5F to 1F, and that's the only thing that is needed for it, the issue occurs in minecraft's collision detection which makes the game think you are unable to pass through the gap (most likely an issue caused by floating point numbers)

**Comment by Entoarox** [comment] 2015-05-25 13:02
@TheWhiteWolves It is not actually an issue with floating point numbers, but when moving upwards, minecraft requires 50% of the block-space you are moving into to be empty air, even if you only need a tiny bit of that block space in actuallity.
This issue should be fixed in 1.8, since single-way soul sand doors no longer work in 1.8 either.

**Comment by TheWhiteWolves** [comment] 2015-05-29 11:39
Nothing we can do about this.

**Comment by Vazkii** [comment] 2015-05-29 16:46
We can disable stepup if the player is inside a block.

**Comment by Vazkii** [comment] 2015-05-29 18:03
On second thought, doing that is a silly idea.

**Closed by Vazkii** 2015-05-29 18:03 UTC
Labels: change
