### ISSUE TITLE
Kindle Lens does not create Soul Fire uzpon hitting Soul sand

### ISSUE THREAD

**Issue by DnielMC** [Vazkii/Botania#4371] opened 2023-05-21 07:16 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-439

### Modloader version

Forge: 43.2.11

### The latest.log file

https://pastebin.com/xbUfErPV

### Issue description

When Soul Sand/Soil is being ignited Soul Fire should be created, but the Kindle Lens does not.

### Steps to reproduce

1. Place Soul Sand/Soil
2. Place Redstone Mana Spreader with Kindle Lens with Mana Pool
3. Point Redstone Mana Spreader at Soul Sand/Soil
4. Activate Redstone Mana Spreader

**Comment by anoomolu** [comment] 2023-05-21 14:13
Think this is a duplicate of #4355.

**Comment by williewillus** [comment] 2023-05-21 16:50
Duplicate of #4355 and should be fixed in the next version

**Closed as not planned by williewillus** 2023-05-21 16:50 UTC
