### ISSUE TITLE
interaction logic between force relay and slime block failed

### ISSUE THREAD

**Issue by 9SENSEI** [Vazkii/Botania#4411] opened 2023-06-26 08:49 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-440

### Modloader version

Forge:43.2.3

### The latest.log file

(n/a)

### Issue description

behavior of slime block and force relay is not consistent with version 1.16.5

https://github.com/VazkiiMods/Botania/assets/56625750/f4fbcb9e-f5fd-4ee9-8e4d-1a620f5e2fca

**Comment by TheRealWormbo** [comment] 2023-12-09 10:08
Looks like a duplicate of #3917.

**Closed as completed** 2023-12-13 15:30 UTC
