### ISSUE TITLE
Strange Rendering Error with Runic Altar

### ISSUE THREAD

**Issue by bunnyman14** [Vazkii/Botania#3291] opened 2020-05-14 04:55 UTC
# Version Information
Forge version:  31.1.74
Botania version:  r1.15-383
MODPACK: Valhelsia 2 Version 2.1.8a
Added Direwolf20's Building and Mining Gadgets mods.
**NO, I AM NOT USING OPTIFINE**
# Further Information
Link to crash log: No crash
Steps to reproduce:
1. First step: Place Runic Altar
2. Second step: Place a valid recipe into the Runic Altar
3. Third Step: As the Runic altar is crafting, hover the cursor over the Runic Altar (so that the progress bar is shown)
4. Watch as the ENTIRE world disappears.

What I expected to happen: The Progress bar to be shown for the item WITHOUT the world disappearing

What happened instead: Rendering F up.
![2020-05-13_21 06 59](https://user-images.githubusercontent.com/7276888/81893919-a8e0a780-957c-11ea-8590-da15b356ca78.png)
![2020-05-14_00 35 04](https://user-images.githubusercontent.com/7276888/81893923-a9793e00-957c-11ea-99d9-195b523f888b.png)

My first suspect was Immersive Portals, but deleting the portal did not solve the issue. Considering this has not been posted elsewhere on this Github, this may be a mod conflict.

**Comment by williewillus** [comment] 2020-05-14 13:27
Duplicate of #3237

**Closed by williewillus** 2020-05-14 13:27 UTC
