### ISSUE TITLE
1.12.2 Problem with corporeal network

### ISSUE THREAD

**Issue by larskr96** [Vazkii/Botania#2617] opened 2018-04-28 23:11 UTC
Hey the requesting from nei/jei With corporeal network is not working and pressing tab to fill the item name is not working like it says in the lexico botania

**Comment by williewillus** [comment] 2018-04-30 06:49
duplicate of #2556 and #1873.

I hope to resolve the #1873 in 1.13, but not sure when #2556 will be reimplemented.

**Closed by williewillus** 2018-04-30 06:49 UTC
