### ISSUE TITLE
crash at login with botania

### ISSUE THREAD

**Issue by Tsukiumy** [Vazkii/Botania#1953] opened 2016-10-18 18:46 UTC
forge-1.10.2-12.18.2.2107.jar
Botania r1.9-332.jar

i started to get this crash today, dont know exactly why, just get the game freezed when entering the world 2 times then get this crash.
http://pastebin.com/txw0MCdB

**Comment by Vazkii** [comment] 2016-10-19 19:30
Dupe of #1950

**Closed by Vazkii** 2016-10-19 19:30 UTC
