### ISSUE TITLE
Trinkets Integration for Botania Fabric's Trinket Box

### ISSUE THREAD

**Issue by Shibva** [Vazkii/Botania#4426] opened 2023-07-21 06:40 UTC
### Mod Loader

Fabric

### Minecraft Version

(varies as long as Trinkets has existed in X versions) [19.2 if you want to be specific]

### Botania version

19.2-440

### Modloader version

farbic 0.14.21

### The latest.log file

(is not a error from what I gathered)

### Issue description

Ive noticed that in the farbic version of Botania that some of the trinkets from other mods that should go into the Trinkets Case wont and after looking into your code here, ive realized its because only Curios intigration was made.

Considering that your trinkets have trinket integration for being used in the Trinket slots, I can only assume that this was most likely an oversight or something that was forgotten to be added to the `isAccessory` check when implementing compatibility with Trinkets (the mod).

### Other information

This could be argued to be a

**Comment by williewillus** [comment] 2023-07-23 18:33
duplicate of #4427

**Closed as not planned by williewillus** 2023-07-23 18:33 UTC

**Comment by Shibva** [comment] 2023-07-23 18:55
I accidentally submit this thing twice it seems XD

Oops
