### ISSUE TITLE
Worldshaper's Astrolabe crash when right clicking with no block set.

### ISSUE THREAD

**Issue by thefinaluptake** [Vazkii/Botania#2028] opened 2016-11-10 18:45 UTC
I get this crash whenever I right click with the Worldshaper's Astrolabe. http://hastebin.com/ubajayipeb

This only happens when I attempt to right click without first shift right clicking on a block. It works fine after setting a block for the Astrolabe to place.

**Comment by Vazkii** [comment] 2016-11-14 22:57
Dupe of #2019

**Closed by Vazkii** 2016-11-14 22:57 UTC
