### ISSUE TITLE
java.lang.NullPointerException: Key may not be null.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Vazkii/Botania#4051] opened 2022-05-25 12:49 UTC
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-432-FABRIC

### Modloader version

Fabric: Loader 0.14.6 + API 0.53.4+1.18.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### The latest.log file

https://bytebin.lucko.me/izU7w4aBfy

### Issue description

I was wandering around, then it crashed.

**Comment by HacoKavanah** [comment] 2022-05-31 20:52
Got same crash.

**Comment by Andre--D** [comment] 2022-10-17 20:07
Have the same crash to desktop. Without Botania it seams ok
[crash-2022-10-17_17.59.59-client.txt](https://github.com/VazkiiMods/Botania/files/9804135/crash-2022-10-17_17.59.59-client.txt)

**Comment by TheRealWormbo** [comment] 2024-07-13 07:32
Likely duplicate of (or strongly related to) #4027. Closing since 1.18 is no longer supported and there are no similar reports for newer versions.

**Closed as not planned by TheRealWormbo** 2024-07-13 07:32 UTC
Labels: compatibility, investigate
