### ISSUE TITLE
Terrasteel crafting disabled

### ISSUE THREAD

**Issue by Noxally** [Vazkii/Botania#3968] opened 2022-02-26 09:40 UTC
### Mod Loader

Fabric

### Minecraft Version

1.18.1

### Botania version

1.18.1-428

### Modloader version

0.13.3 and 0.46.4

### The latest.log file

n/a

### Issue description

Terrasteel crafting has been disabled, along with the lexicon's entry regarding the structure rendering bedrock blocks instead of lapis blocks in the multiblock.

### Steps to reproduce

1. Build the terrestrial agglomeration multiblock
2. Attach a spark or point a mana spreader at it
3. Throw mana pearl, mana diamond and manasteel ingot
4. Wait 4 years while nothing happens

### Other information

This issue doesnt exist in 1.18.1-427

**Comment by Hubry** [comment] 2022-02-26 11:33
Duplicate of https://github.com/VazkiiMods/Botania/issues/3962

**Closed as completed** 2022-02-26 11:33 UTC
