### ISSUE TITLE
flowers disappearing

### ISSUE THREAD

**Issue by ZakStrassberg** [Vazkii/Botania#1162] opened 2015-07-12 01:56 UTC
My mana generating flowers are disappearing during play.

Twice now my Day Blooms and Hydroangeas have disappeared randomly as I was in the area. Just now I was AFK waiting for a mana tablet to fill; a couple minutes later (less than 10) all my flowers were gone. I don't see any errors in the dedicated server's console so I can't give you any logs unless you know where I should look.

I'm running Botania r1.7-201.jar so everything is up to date. I'm running a custom pack put together by some friends. 

Thanks for the help and for maintaining such an awesome mod!

**Comment by MrKunji** [comment] 2015-07-12 02:02
The flowers are simply withering, it's natural. This can be disabled via config, for now it's forced to two days.
Also, read the changelog, this change was mentioned there.

**Comment by ZakStrassberg** [comment] 2015-07-12 02:24
I don't think it was 2 days worth of time in game (only a few minutes IRL), but I'll change configs and see that fixes it. If I set it to 0, will it turn off withering?

OTOH Pure Daisy didn't disappear

**Comment by MrKunji** [comment] 2015-07-12 02:31
Only passive generating flower (Dayblooms, Nightshades and Hydroangeas) can wither away.
Set the time to -1, there's a tip saying that in the config description.

**Comment by jHoyne** [comment] 2015-07-12 02:35
Is there a config to change withering time altogether to any specifics via
configs or is it a 0 or 1 type thing

On 11 July 2015 at 21:31, Patric Alexandre <notifications@github.com> wrote:

> Only passive generating flower (Dayblooms, Nightshades and Hydroangeas)
> can wither away.
> Set the time to -1, there's a tip saying that in the config description.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vazkii/Botania/issues/1162#issuecomment-120680586>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by ZakStrassberg** [comment] 2015-07-12 02:36
Looks like you set the # of ticks. 24000 (2 minecraft days) is the default. I dunno what 0 would do, but -1 is never.

**Comment by jHoyne** [comment] 2015-07-12 02:38
0 would be every tick wouldn't it

On 11 July 2015 at 21:36, Zak Strassberg <notifications@github.com> wrote:

> Looks like you set the # of ticks. 24000 (2 minecraft days) is the
> default. I dunno what 0 would do, but -1 is never.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Vazkii/Botania/issues/1162#issuecomment-120680705>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>

**Comment by MrKunji** [comment] 2015-07-12 02:40
It's not an actual issue, you better close it to prevent confusion :)

**Closed** 2015-07-12 04:25 UTC

**Comment by vzelmanov** [comment] 2015-07-14 06:42
Hey @MrKunji 

We were caught by surprise with this as well, and we didn't see anything in the [changelog](http://botaniamod.net/changelog.php) about it being on by default.

**Comment by SquidDev** [comment] 2015-07-14 06:44
Under R1.6 193
> Hardcore Passive Generation is now enabled by default at 2 days (24000 ticks). This is the config that makes passive flowers decay after some time. Old configs won't be affected, but you should change yours to reflect this, especially if you're a modpack author (please D:).

**Comment by vzelmanov** [comment] 2015-07-14 06:46
Thanks @SquidDev! That wasn't immediately obvious.

**Comment by DJWigglebottoms** [comment] 2015-12-07 00:24
I Looked in the configs of this modpack i'm playing and i can not find the  default setting/code to turn off flower decay please help me.

**Comment by yrsegal** [comment] 2015-12-07 00:24
This is intended behavior, @DJWigglebottoms.

**Comment by DJWigglebottoms** [comment] 2015-12-07 00:26
but can i change it?

**Comment by yrsegal** [comment] 2015-12-07 00:26
@DJWigglebottoms No. The ability to do that was removed a while ago.

**Comment by DJWigglebottoms** [comment] 2015-12-07 00:27
Ok thanks
