### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by knoxhack** [Vazkii/Botania#4533] opened 2024-01-02 15:29 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-442-FORGE

### Modloader version

47.2.18

### Modpack info

Fantasy Skies

### The latest.log file

https://gist.githubusercontent.com/knoxhack/7afd7ce5a24ce7b9cbdab538c16ab676/raw/44c3a04edce3fc93a721c9917969d7121dc8c9a1/botania

### Issue description

crash on server when generating chunks

### Steps to reproduce

crash on server when generating chunks

### Other information

Crash report file:
https://gist.githubusercontent.com/knoxhack/7afd7ce5a24ce7b9cbdab538c16ab676/raw/44c3a04edce3fc93a721c9917969d7121dc8c9a1/botania

**Comment by TheRealWormbo** [comment] 2024-01-02 15:48
Duplicate of #4527, fixed by #4528 in an upcoming version.

**Closed as not planned** 2024-01-02 15:49 UTC
