### ISSUE TITLE
Mixin conflict with UniqueBase

### ISSUE THREAD

**Issue by Yourname942** [Vazkii/Botania#4310] opened 2023-03-09 22:09 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-438-FORGE  

### Modloader version

Forge 43.2.6

### Modpack info

I am making a mod and is not uploaded yet

### The latest.log file

https://gist.github.com/Yourname942/145468d79274234671c76d1a1b0300ac

### Issue description

Here is the crashlog https://pastebin.com/s9281DVn

### Steps to reproduce

1. Launch Curseforge standalone version
2. Select the modpack
3. Select Play
4. create a new installation (1.19.2)
5. launch minecraft
6. crash during the loading

### Other information

Here is the modpack that I have so far: https://drive.google.com/file/d/1zUtcZKmgmHA1t4lPBkTfACMexr-NZKKB/view?usp=sharing

It looks like something to do with mixins between Botania and Apotheosis. Is this incompatible? 
at line 2368:
```
[16:45:40] [Render thread/FATAL]: Mixin apply failed uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin -> net.minecraft.world.item.enchantment.EnchantmentHelper: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("TAIL")] on net/minecraft/world/item/enchantment/EnchantmentHelper::removeApexEnchantments with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [PREINJECT Applicator Phase -> uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin -> Prepare Injections ->  -> handler$cmh000$removeApexEnchantments(ILnet/minecraft/world/item/ItemStack;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("TAIL")] on net/minecraft/world/item/enchantment/EnchantmentHelper::removeApexEnchantments with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [PREINJECT Applicator Phase -> uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin -> Prepare Injections ->  -> handler$cmh000$removeApexEnchantments(ILnet/minecraft/world/item/ItemStack;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V -> Prepare]
```

**Comment by anoomolu** [comment] 2023-11-28 10:06
Duplicate of https://github.com/VazkiiMods/Botania/issues/4345, which has already been closed as being not Botania-related.

**Closed as not planned by anoomolu** 2023-11-28 10:06 UTC
