### ISSUE TITLE
Wearing anything in cosmetic armor slots and Botania armor in actual armor slots crashes Minecraft

### ISSUE THREAD

**Issue by drown3d** [Vazkii/Botania#4285] opened 2023-02-05 22:53 UTC
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-435

### Modloader version

Fabric 0.14.10

### Modpack info

https://www.curseforge.com/minecraft/modpacks/ultimate-origins-modpack

### The latest.log file

https://pastebin.com/7bjadBv2

### Issue description

When Cosmetic Armor (https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric) is installed and the player wears Botania armor in their vanilla armor slots and anything else in their cosmetic armor slots, the game crashes.

### Steps to reproduce

1. Wear any Botania armor
2. Put any other armor (for example netherite) in the cosmetic armor slots
3. The game will crash

### Other information

Crash report https://pastebin.com/NEsRBS4U

**Comment by anoomolu** [comment] 2023-05-29 18:16
There's likely another mod in your pack that's involved in this issue. I wasn't able to reproduce the issue with latest FAPI, Botania, Trinkets and Cosmetic Armor. 

![image](https://github.com/VazkiiMods/Botania/assets/77850233/06705786-6e13-4363-b31b-2f963676864c)
![image](https://github.com/VazkiiMods/Botania/assets/77850233/ed6038f3-428a-4830-bd2c-b89d0afb11d6)

Both Terrasteel and Manasteel armour sets were working fine with netherite in the cosmetic slots.

**Comment by anoomolu** [comment] 2023-11-22 11:04
Closing this as I can't reproduce it with just Cosmetic Armor Slots and Botania. Disabling half the mods in your modlist (obviously not including the relevant dependencies) may help you track down the mod responsible.

**Closed as not planned by anoomolu** 2023-11-22 11:04 UTC
