### ISSUE TITLE
Mana chapter vanished

### ISSUE THREAD

**Issue by Thunderlagger** [Vazkii/Botania#4582] opened 2024-03-20 16:20 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.20.1-443

### Modloader version

Forge 1.19.2 - 43.3.0

### The latest.log file

https://gist.github.com/Thunderlagger/7b1b078d264da2fd57b022d658ad4673

### Issue description

Mana chapter missing

### Steps to reproduce

1 follow chapters of botania book
2 unlock mana chapter
3 close book
4 chapter and entries disapper

**Comment by TheRealWormbo** [comment] 2024-03-22 17:48
The log suggests Botania is by far not the only mod that is having issues with your configuration.
As for the book's unlocked chapters: Those depend on hidden advancements. If any of your mods messes with advancements, Botania (or actually Patchouli) may no longer know that you unlocked anything in particular.

**Comment by TheRealWormbo** [comment] 2024-05-17 06:11
I'm going to close this issue, since it's unlikely to be something Botania is able to fix. The unlocking mechanic of the Lexica Botania is entirely implemented by Patchouli, Botania merely provides the book's content and unlock conditions – which are confirmed to generally work.

The supplied log also shows a lot of various errors and warnings that are not related to Botania either, but suggest that the combination of mods you are running has not been configured properly. The resulting issues may have contributed to the Patchouli problems you reported here.

**Closed as not planned by TheRealWormbo** 2024-05-17 06:11 UTC
