### ISSUE TITLE
Marimorphosis Crash

### ISSUE THREAD

**Issue by robbitay** [Vazkii/Botania#2261] opened 2017-05-11 19:42 UTC
The game crashed the first tick after putting down the marimorphosis in the Direwolf20 v1.10.2 FTB modpack. Maybe because I had some chiseled marble next to it? Other than that I can't think of anything I did weird... Hopefully the crash reports help. The first is the initial crash. Second in is me force shutting down the game because it was frozen. Third was another crash.
[crash-2017-05-11_12.01.46-server.txt](https://github.com/Vazkii/Botania/files/994217/crash-2017-05-11_12.01.46-server.txt)
[crash-2017-05-11_12.16.42-server.txt](https://github.com/Vazkii/Botania/files/994218/crash-2017-05-11_12.16.42-server.txt)
[crash-2017-05-11_12.34.59-server.txt](https://github.com/Vazkii/Botania/files/994219/crash-2017-05-11_12.34.59-server.txt)

**Comment by Tamaized** [comment] 2017-05-11 19:45
dupe of #2197

**Comment by robbitay** [comment] 2017-05-11 19:47
Oh shoot, sorry to post it again. Looks like its been fixed just not pushed in an update? Should I leave this issue or delete it?

**Comment by Tamaized** [comment] 2017-05-11 19:48
Can't delete issues only close and I assume @williewillus is gonna close it either way.

**Comment by williewillus** [comment] 2017-05-12 21:40
it's fixed in 1.11, unfortunately not in 1.10

**Closed by williewillus** 2017-05-12 21:40 UTC
