### ISSUE TITLE
Botania Armor + Extra Utilities 2 spikes cause crash

### ISSUE THREAD

**Issue by Cri16228** [Vazkii/Botania#2887] opened 2019-04-12 19:18 UTC
# Version Information
Forge version: 14.23.5.2808
Botania version: Botania r1.10-360

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\ https://gist.github.com/Cri16228/83af9e1e3cdea9829ead695af42da14a
My previous report: https://github.com/Vazkii/Botania/issues/2886 
Steps to reproduce:
1. Wear a full manasteel armor
2. Wear a band of mana
3. Die in an Extra Utilities Spike :D (No, this is not a joke. I did and it crashed)

**Comment by Hubry** [comment] 2019-04-12 21:49
Duplicate of #2886, basically.

**Comment by Cri16228** [comment] 2019-04-12 21:51
Yes, sorry if I opened 2 issues post. I didn't know was the same problem

**Closed** 2019-04-13 16:30 UTC
