### ISSUE TITLE
Loonium creepers giving near-infinite potion effects on explosion

### ISSUE THREAD

**Issue by bokke1010** [Vazkii/Botania#2511] opened 2018-01-11 19:31 UTC
Forge version: 8.0.99.99
Botania version: r1.10-350
Link to crash log: no crash
Steps to reproduce:
1. Setup a loonium
2. Wait untill a creeper spawns
3. Let it explode
4. Get a near-infinite duration potion effect

What I expected to happen:
Loonium spawned creeper explodes, maybe giving a limited time lingering potion
What happened instead:
Loonium spawned creeper will spawn a practically unlimited time lingering potion effect on explosion

**Comment by williewillus** [comment] 2018-01-11 20:20
duplicate of #2233

**Closed by williewillus** 2018-01-11 20:20 UTC
