### ISSUE TITLE
Shader issues

### ISSUE THREAD

**Issue by CariedRanger** [Vazkii/Botania#4778] opened 2024-12-31 16:10 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-446

### Modloader version

Forge - 47.3.0

### Modpack info

https://www.curseforge.com/minecraft/modpacks/adventure-craft-by-aidenmouse/files/all?page=1&pageSize=20

### The latest.log file

No idea why a loog would be needed 

### Issue description

A lot of things bug out, if you have a shader turned on. All Pylons inner Part dissapeares, the maan in the pools is no longer visable and the pink star projector turns into an xray window. Im using Complimentaey reimagend

### Steps to reproduce

1. Start game 2. place any of the named blocks down 3. activate a shader 4. observe I guess

**Comment by TheRealWormbo** [comment] 2024-12-31 23:12
Duplicate of #3951

**Closed as not planned by TheRealWormbo** 2024-12-31 23:12 UTC
