### ISSUE TITLE
Marimorphosis crashing 1.10.2 - r1.9-341

### ISSUE THREAD

**Issue by MarkSzita** [Vazkii/Botania#2249] opened 2017-04-22 10:10 UTC
This was tested in single player on a clean 1.10.2 client.
Crash Log - https://pastebin.com/vBRLdks9

The Marimorphosis will convert a couple of stone blocks placed down just fine. but if there are a lot around it to convert it goes through them too quickly and crashes. at least that's what it looks like.

Hopefully that's all it is, and it can just be slowed down.

**Comment by williewillus** [comment] 2017-04-22 13:38
duplicate of #2197

**Closed by williewillus** 2017-04-22 13:38 UTC
