### ISSUE TITLE
Boss music is a stereo ogg

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#4065] opened 2022-06-06 04:15 UTC
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.18.2

### Botania version

433-FABRIC-SNAPSHOT or whatevers on blanketcon idk

### Modloader version

Ur mom

### The latest.log file

Ur mom

### Issue description

The boss music is in stereo, which Minecraft's engine has trouble with for some reason. For example, jukeboxes with the music disc inside play the boss music at the same volume no matter how far away you go from the jukebox.

### Steps to reproduce

1. Place jukebox
2. Place botania music disk inside
3. Everyone on blanketcon gets a Botania Jumpscare

**Comment by Fusion-Flux** [comment] 2022-06-06 04:16
10/10 would be jumpscared again

**Comment by williewillus** [comment] 2022-06-06 06:17
Duplicate of #3584

**Closed as not planned by williewillus** 2022-06-06 06:17 UTC
