### ISSUE TITLE
Cocoon of Caprice has no texture in inventory

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Botania#1211] opened 2015-07-26 13:58 UTC
build 207
<img width="448" alt="screen shot 2015-07-26 at 9 58 16 am" src="https://cloud.githubusercontent.com/assets/6596492/8894233/e64072b6-337c-11e5-96c7-82f6ae6462e5.png">

**Comment by SquidDev** [comment] 2015-07-26 14:22
Duplicate of #1200 and  #1191. Vazkii can't reproduce though.

**Comment by Kubuxu** [comment] 2015-07-26 14:23
As I said:
```
It might be connected with fact that older GFX require square textures and/or power of two dimensions.
```
It might not be possible to reproduce as it is hardware thing. Just change textures to square of length of power of 2.

**Comment by yrsegal** [comment] 2015-07-26 14:25
I have a recent graphics card, though; the `Nvidia GeForce GT 750M`. Would that possibly be affected by it?

**Comment by yrsegal** [comment] 2015-07-26 14:28
In addition, I used to be able to render Prisms, but not anymore...

**Closed** 2015-07-26 15:13 UTC
