### ISSUE TITLE
Thermally not generating mana

### ISSUE THREAD

**Issue by Sto3IV** [Vazkii/Botania#2615] opened 2018-04-26 12:05 UTC
Thermally eating too much lava.
And not generating mana.
Video: https://youtu.be/fTlADjcrgPg

**Comment by williewillus** [comment] 2018-04-26 13:12
What botania version? A two year old bug where the thermaliky was not penalizing for giving it lava while on cooldown was fixed in the latest build. This is intended behaviour. Read the lexicon for details.

**Comment by Sto3IV** [comment] 2018-04-26 14:35
354 Botania version. 
1.12.2 minecraft. 
Latest forge.

**Comment by Sto3IV** [comment] 2018-04-26 14:36
Infinite fluids mod for infinite lava.

**Comment by williewillus** [comment] 2018-04-26 14:41
yes, this is the intended behaviour. Previous behaviour was a bug. 

If you give the flower more lava while it is still on cooldown (emitting gray particles), it will eat it and not produce mana. You will have to time the lava carefully.

**Closed by williewillus** 2018-04-26 14:41 UTC

**Comment by williewillus** [comment] 2018-04-27 00:16
please read the lexicon. You must not give it any lava while it is emitting gray particles, or else cooldown starts over.
