### ISSUE TITLE
Planestrider's Sash doesn't increase speed

### ISSUE THREAD

**Issue by Mariadevis** [Vazkii/Botania#4383] opened 2023-05-28 14:08 UTC
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.3

### Modloader version

Forge: 36.2.34

### The latest.log file

n/a

### Issue description

**When trying to run around with a Planestrider's sash, I can't get any acceleration.**
I didn't check for any slight speed boost as I didn't have tools to measure my character's speed, sorry. But from raw observations, **there isn't any speed boost**. **The step assist still works.**
Thank you for your work. Have a good day.

### Steps to reproduce

1. Launch the game and load a world
2. Equip the Planestrider's sash and a filled mana tablet
3. Try catching speed by running around
4. If the issue takes its roots in the mod alone or in its dependencies, the acceleration would not occur

### Other information

- Patchouli version **116.4-53.2**
- Curios API version **1.16.5-4.0.8.2**.
- Launched with MultiMC 5
- Windows 10

**Comment by williewillus** [comment] 2023-05-28 15:57
How long were you testing it for? The sash's effect takes a while to notice.

**Comment by anoomolu** [comment] 2023-05-28 16:21
Managed to reproduce with just Botania + deps, weird because it works in 1.15.2, and on latest, but not 1.16.5.

Looks like all 1.16.5 versions have this issue.

**Comment by Mariadevis** [comment] 2023-05-28 16:44
> How long were you testing it for? The sash's effect takes a while to notice.

I was testing it for a solid minute

**Comment by williewillus** [comment] 2023-05-29 00:01
It works in 1.19, so I don't know what to say. We don't really have resources to maintain 1.16 any further, so unless someone sends in a patch I can't promise anything.

**Comment by WebDragon** [comment] 2023-07-01 16:10
If this helps you reproduce the bug, I am able to reproduce this in the current (and very recent, still-in-beta)  FTB Integration-by-Parts-DX modpack. same version, though patchouli is 1.16.4-53.3 in this pack, and Curios API is 1.16.5-4.1.0.0 

Ran the entire distance down my mining tunnel with no appreciable increase in speed. Quite disconcerting.

**Comment by anoomolu** [comment] 2023-11-22 17:59
Nothing's really changed code-wise for the Planestrider Sash if you check the PlanestridersSashItem.java class history, and it works on all other versions so I'm closing this. Might just be Forge jank.

**Closed as not planned by anoomolu** 2023-11-22 17:59 UTC
Labels: cant-reproduce
