### ISSUE TITLE
Warped mana bursts can enter pools if they go through a Mana Prism

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Botania#3164] opened 2020-02-02 21:02 UTC
Reporting this on behalf of auxchar :stuck_out_tongue_winking_eye: 

After warping a mana burst with the Warp lens and a force relay, it's not supposed to go into mana pools.

However, mana prisms remove the "warped" state, so passing the burst through a prism after it warps but before it reaches the pool will allow it to enter.

r1.11-376 ~~which is the version i assume aux is using~~

**Comment by auxiliary-character** [comment] 2020-02-02 21:10
I thought this was intended behavior, sorry. :man_facepalming: 

Anyways,
>r1.11-376 which is the version i assume aux is using

No, this is actually incorrect. I do my own builds, since sometimes I see new features I want to play with before they're officially released. Last time I built was at `ea30c6aa4`, though it probably doesn't matter much since the affected code hasn't been touched in quite a while anyways.

**Comment by Hubry** [comment] 2020-02-02 21:18
imagine not using builds from https://ci.blamejared.com/job/Botania/job/master/

**Comment by auxiliary-character** [comment] 2020-02-02 21:23
Meh, it's just a matter of `git pull origin master` and `./gradlew build` for me, tbh. Honestly, more work to go there in my browser.

**Comment by Hubry** [comment] 2020-02-02 21:52
Anyways, closed in 10ac3c3067db14f33ab132c33e42aa0af6d4ef27

**Closed by Hubry** 2020-02-02 21:52 UTC
