### ISSUE TITLE
Greater band of mana has the same capacity as regular band of mana

### ISSUE THREAD

**Issue by umnikos** [Vazkii/Botania#4073] opened 2022-06-19 15:40 UTC
### Mod Loader

Fabric

### Minecraft Version

1.18.2

### Botania version

1.18.2-433

### Modloader version

Fabric: Loader 0.14.6 + API 0.53.0

### The latest.log file

https://pastebin.com/ECQNYZaT

### Issue description

A greater band of mana has the same capacity as a regular band of mana. It doesn't seem to matter if the band was crafted or gotten from the creative mode menu. Getting a full greater band of mana from the creative mod menu does indeed have 4x the mana of a regular band of mana, but it looks like this:

![Screenshot from 2022-06-19 18-35-13](https://user-images.githubusercontent.com/22576233/174489039-941218c0-227a-4793-a85d-1f13289dfa99.png)

### Other information

I am using PolyMC in offline mode, in case that makes a difference.

**Comment by williewillus** [comment] 2022-06-19 16:34
Duplicate of #4069, will be fixed in next release (which should be coming this week ish)

**Closed as not planned by williewillus** 2022-06-19 16:34 UTC
