### ISSUE TITLE
[1.10.2] Server crash when breaking a mana pool - java.lang.IllegalArgumentException: Cannot get property

### ISSUE THREAD

**Issue by ProsperCraft** [Vazkii/Botania#1955] opened 2016-10-18 21:21 UTC
Crashlog - http://pastebin.com/gJg33Ypq

Player says he was trying to break a mana pool.

Description: Ticking block entity
 
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.PoolVariant, values=[DEFAULT, CREATIVE, DILUTED, FABULOUS]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at vazkii.botania.common.block.tile.mana.TilePool.getCurrentMana(TilePool.java:410)
    at vazkii.botania.common.block.tile.mana.TilePool.isFull(TilePool.java:122)
    at vazkii.botania.common.block.tile.mana.TileSpreader.tryShootBurst(TileSpreader.java:440)
    at vazkii.botania.common.block.tile.mana.TileSpreader.func_73660_a(TileSpreader.java:264)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:195)
    at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjk000(WorldServer.java:1294)
    at net.minecraft.world.World.func_72939_s(World.java:1256)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by chayde** [comment] 2016-10-18 21:23
The pool was empty, I tried to break it with an S Rank terra shatterer

**Comment by williewillus** [comment] 2016-10-19 00:42
Forge is letting TE's persist one tick after their block have been broken and idk why .-.

**Comment by Tsukiumy** [comment] 2016-10-19 00:51
i was looking, and most of the last reports seems to be related to this, and in some cases its note related to breaking the mana pool or the spreader. '-'

**Comment by chayde** [comment] 2016-10-19 00:53
Yep I didn't try breaking the spreader first, but its happened 3 times trying to break specific pools.

**Comment by Vazkii** [comment] 2016-10-19 19:26
Dupe of #1955

**Closed** 2016-10-19 19:26 UTC
