### ISSUE TITLE
Pouch losing all flowers randomly...

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Vazkii/Botania#1894] opened 2016-09-24 11:57 UTC
I have no idea what's causing this, but my pouch is losing all the collected flowers randomly.

Forge: 2094
Botania: Botania r1.9-323.jar
More mods: https://gist.github.com/anonymous/1c87d469fb7017a15196a39dac963773

**Comment by Vazkii** [comment] 2016-10-11 17:22
Can anyone at all reproduce this?

**Comment by KomradeSpectre** [comment] 2016-10-12 01:00
I've been able to reproduce the issue on a very similar mod setup, the issue happened to be optifine on that one making items vanish from the inventory until entering any block. The issue with the flower pouch did occur, but vanished the moment optifine was removed.

**Comment by 4rz0** [comment] 2016-10-30 11:38
I can reliably reproduce this by putting the flower pouch inside a Backpacks! backpack.
When the backpack is closed, all flowers inside the pouch are removed.

**Comment by ridjack** [comment] 2016-10-30 18:35
I can confirm the above comment from 4rz0 as well.

**Comment by bookerthegeek** [comment] 2016-10-30 21:14
That actually from a server standpoint is most likely a good thing. Storage inception causes nbt data overload.

Would request that the flower pouch be blacklisted from entering other portable storage, such a a golden bag of holding or backpacks.

**Comment by ridjack** [comment] 2016-10-30 22:39
I mean, the "Backpacks!" mod has you putting backpacks inside of backpacks inside of backpacks. It's kinda all about 'storage inception.'

**Comment by bookerthegeek** [comment] 2016-10-30 22:44
True. And after your player data file needs to be reset or edited you usually don't do it again. 

Most servers just script it to stop storage inception. Editing player data is a pain when you have to do it multiple times a day.

**Comment by JRoffel** [comment] 2016-10-30 22:57
To be fair, since the flower pouch itself doesn't support storing anything other than flowers (therefore not itself) the storage inception part is not at all botanias problem, but more "backpacks!" problem, should probably take that up with them.

**Comment by williewillus** [comment] 2016-10-31 01:20
I am still curious what technically is wrong. I suspect the Backpacks! mod is doing something that only considers the main stack NBT tag, except that these flowers are stored in the capability NBT tag.

**Comment by bookerthegeek** [comment] 2016-10-31 03:40
@JRoffel very true

@williewillus Sorry for the rant.

**Comment by 4rz0** [comment] 2016-10-31 07:55
Well, storing other things that can contain things works (IE crates, bits bag), so Botania must be doing something different than the other mods.

**Comment by williewillus** [comment] 2016-10-31 12:29
Botania uses the new capability system for this inventory, do the other mods use it?

**Comment by 4rz0** [comment] 2016-10-31 15:45
Don't think so. Doesn't look like there was a need for that since everything worked as intended.

**Comment by williewillus** [comment] 2016-10-31 15:57
Okay, so it's the Backpacks mod not supporting the new capabilities. do they have a repo?

**Comment by 4rz0** [comment] 2016-10-31 15:59
Not that I know of.
I'll see if I can contact the creator about that problem.

**Comment by Febilian** [comment] 2016-11-01 23:21
I actually just had my flower pouch AND my baubles case randomly empty themselves twice now. I don't know when it happened the first time, but as soon as I noticed I went into creative on my dedicated server to return the items lost to the glitch, and immediately my baubles case was empty again when I checked it.

One thing to note: I don't have the same backpack mod installed as the other people have mentioned in this issue(I have Iron Backpacks instead), nor was I even putting the baubles case/flower pouch anywhere but in my main inventory. They were in my inventory the entire time yet managed to erase all of their contents somehow.

I don't know what's causing it to begin with, but the fact that it happened to me again immediately after going into creative mode to try and fix it may be a clue.

It is also true that I went into creative earlier today in order to test out some things(also on the dedicated server), and it's possible that I simply didn't notice that my flower pouch/baubles case were empty until after the fact; I was focusing on other mods for a while after all, and hadn't had a need to open either.

**Comment by Tamaized** [comment] 2016-11-02 02:22
^ I've actually noticed this myself with my own mod with any items that have capabilities, looking at a creative window that contains the items would reset them but I just assumed its my own faulty code.

**Comment by williewillus** [comment] 2016-11-02 03:10
might be a forge thing then

**Comment by williewillus** [comment] 2016-11-09 02:07
Possible forge bug: https://github.com/MinecraftForge/MinecraftForge/issues/2523

**Comment by 4rz0** [comment] 2016-11-09 13:31
Sounds very plausible, thanks for finding this!

**Comment by RobertLSnead** [comment] 2017-01-09 00:24
Ugh.  I just experienced this bug!

**Comment by RobertLSnead** [comment] 2017-01-09 01:26
Yes!  I just updated my server to 12.18.2.2185 and see if that fixes the bug.  Most of the posts are blaming Forge so I updated to see if it fixes the bug.  So far so good.  I noticed that it goes to zero then fills in the flowers.  Hopefully this fixes it.

**Comment by macks2008** [comment] 2017-05-22 03:27
I've noticed this happen if I load an NEI cheat mode "save" state that happens to contain a flower pouch. No matter what the pouch contained when I saved it, the pouch loaded by NEI is empty. 
Any chance you guys can release a hot fix that just uses standard NBT for now? What does compat NBT even do differently anyway?

**Comment by Tamaized** [comment] 2017-05-22 03:35
The capability system allows for more control over stuff and helps out with other mod interactions as well if needed. Last time I looked into this, I could be wrong here, the cap system doesn't update the nbt every single tick meanwhile the non-cap system does. It's a wonderful tool for us modders.

**Comment by macks2008** [comment] 2017-06-07 17:03
@Tamaized So those of us that prefer 1.10 for whatever reason (such as the unfortunate fact a lot of mods haven't updated to 1.11 yet) are probably SoL on this issue? Great....

**Comment by ktole1999** [comment] 2017-06-07 17:35
alot of devs are getting to the point of not supporting multiple versions due to time available. i can understand both sides. it is what it is.

**Comment by Hubry** [comment] 2020-01-11 00:13
Go away stale. This still happens, though it's not really reliable. Might need to move to saving the cap on the stack NBT.

**Comment by dgobi** [comment] 2020-02-05 13:16
This just happened to me. The only inventories other than my player one the pouch was placed in was a gold chest from the Iron Chests mod. This was in survival mode. The modpack I'm plying is Arcane Anarchy (and it does contain inventory auto sort, Quark, etc) https://www.curseforge.com/minecraft/modpacks/arcane-anarchy

**Comment by Brycey92** [comment] 2020-04-14 18:02
I'm also having this problem in 1.12.2, and I'm using creative mode, Thermal Expansion satchels, and inventory sorting.

**Comment by OfficialStamper** [comment] 2020-05-17 20:23
This just happened to me, lost all flowers except the brown ones, after having mistakenly clicked the middle mouse button, which would normally sort inventory.

I suspect the Inventory Sorting mods are at fault.

**Comment by Brycey92** [comment] 2020-07-28 01:00
Issue is still present, please reopen, Mr. Bot!

**Comment by ForgottenHero** [comment] 2020-09-09 08:57
I'm using FTB Omnia which includes **Simple Inventory Sorter** mod.
By middle-mouse-clicking (default key to sort) when I have the flower pouch open, it deleted all flowers except for the stack of Mystical Red Flowers.

**Comment by Hubry** [comment] 2020-09-09 09:02
@ForgottenHero cpw/inventorysorter#89

**Comment by Hubry** [comment] 2021-01-22 17:37
I believe this is now fixed after 66bd3ae399ed750e97545bbb4fcac5686fc196d1 and 4bbf5fe08d572e74f958926c6ded0416cc9a8e1d putting contents into main item NBT.

**Closed** 2021-01-22 17:38 UTC
Labels: confirmed, investigate

**Comment by Hubry** [comment] 2021-10-16 00:09
Nope, 1.12.2 is only going to get critical bug fixes (which is still quite a lot of support). *Trivial* backports may come with them, but the scope of the change fixing this was decently large and the gain is very low - especially when the workaround is simply not going into creative when holding the pouch.

**Comment by DoomRater** [comment] 2021-10-16 00:36
If the same thing happens to the Immersive Engineering Toolbox, there may not be much the Botania team can do about it.

**Comment by TheRandomCrafter83** [comment] 2022-06-10 18:43
Same thing happens to me. however, mine happens with inventory sorting. I had some flowers in the pouch. accidentally clicked the mouse wheel, which sorts items in an inventory. Almost all of the flowers disappeared. all that was left were the mystical white flowers and the mystical red flowers. everything else was gone. I am using the newest Direwolf 20 modpack btw.

**Comment by Krougal** [comment] 2022-06-10 18:55
> Same thing happens to me. however, mine happens with inventory sorting. I had some flowers in the pouch. accidentally clicked the mouse wheel, which sorts items in an inventory. Almost all of the flowers disappeared. all that was left were the mystical white flowers and the mystical red flowers. everything else was gone. I am using the newest Direwolf 20 modpack btw.

If it's in 1.12.2 then it is likely CPW Inventory Sorter. I believe the issues been corrected/or just resolved itself in later versions but was never backported.  If you're in some other version then I don't know.

**Comment by TheRandomCrafter83** [comment] 2022-06-10 19:04
> > Same thing happens to me. however, mine happens with inventory sorting. I had some flowers in the pouch. accidentally clicked the mouse wheel, which sorts items in an inventory. Almost all of the flowers disappeared. all that was left were the mystical white flowers and the mystical red flowers. everything else was gone. I am using the newest Direwolf 20 modpack btw.
> 
> If it's in 1.12.2 then it is likely CPW Inventory Sorter. I believe the issues been corrected/or just resolved itself in later versions but was never backported. If you're in some other version then I don't know.

I suppose I should mention the latest Direwolf20 pack is 1.18.2 version of minecraft.
