### ISSUE TITLE
[1.16.1] Optifine: Game crashes when rendering botania:mana_pylon in JEI

### ISSUE THREAD

**Issue by NillerMedDild** [Vazkii/Botania#3409] opened 2020-08-16 21:04 UTC
# Version Information
Forge version:  1.16.1-32.0.108
Botania version:  1.16-402

# Further Information
https://paste.ee/p/EcNoY
Steps to reproduce:
1. Make an instance with Optifine + Botania + JEI
2. Search for Mana Pylon
3. Crash

What I expected to happen:
No crash.

What happened instead:
Crash.

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/154

**Comment by Hubry** [comment] 2020-08-16 21:45
![obraz](https://user-images.githubusercontent.com/26120076/90344458-49ca7d00-e01a-11ea-9b1d-da68608005d4.png)

Anyways, grab Forge 32.0.106, something in 107's cleanups breaks Optifine.
Duplicate of #3403, fixed by 1069ebb770859fd176b432d7183cd0b706615698

**Closed by Hubry** 2020-08-16 21:45 UTC
