### ISSUE TITLE
Tile entities are not rendered through sparks

### ISSUE THREAD

**Issue by TheNoseOfSauron** [Vazkii/Botania#2789] opened 2018-11-27 22:02 UTC
# Version Information
Forge version:  1.12.2 - 14.23..5.2768
Botania version:  r1.10-357

Tile entities such as chests and mana in mana pools are not rendered through sparks, as shown in the screenshot in the attached link.
https://imgur.com/a/y19n5Ls

**Comment by Hubry** [comment] 2018-11-27 22:16
Duplicate of #2736, see also #2719.

**Comment by williewillus** [comment] 2018-11-28 06:02
dupe

**Closed by williewillus** 2018-11-28 06:02 UTC
