### ISSUE TITLE
Mana pool CTD

### ISSUE THREAD

**Issue by dvdmcwilliams** [Vazkii/Botania#3077] opened 2019-12-28 18:23 UTC
#2101 Version Information
Forge version:  14.23.5.2846
Botania version:  r1.10-361

# Further Information
Link to crash log: https://paste.feed-the-beast.com/view/b6d51fd8
Steps to reproduce: No steps at all, it occurs randomly

My game crashes whenever i teleport to someone with mana pools around, or randomly in my base, i cant use botania mod, when i want to fill the pools they remain with the initial load and stay as is, tried gourmarillys, and endoflames, they are linked to the spreader and it to the pool, but it wont fill, the admin of the server i play daily made a fix to my botania jar, it prevents me to crash with botania stuff around, but as i said mana pools wont fill, which makes the mod totally unusable, if i come back to the unedited botania jar (the one who comes with ftb revelation pack) the game crash everytime as stated above.
I could avoid the CTD by adding vanillafix to the mods folder, at least wont have to reload the game everytime it crash, altought the problem persists.

**Comment by Hubry** [comment] 2019-12-28 22:12
Duplicate of #2205. You have VoxelMap, which seems to be the most common source of this - try replacing it with another map mod like Xaero's Minimap, or JourneyMap.

**Closed by Hubry** 2019-12-28 22:12 UTC
