### ISSUE TITLE
Tiara Repeated Dashes while Sprinting

### ISSUE THREAD

**Issue by bcrotty** [Vazkii/Botania#4056] opened 2022-06-04 18:50 UTC
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.2

### Modloader version

Forge 36.2.31

### Modpack info

https://www.curseforge.com/minecraft/modpacks/valhelsia-3

### The latest.log file

My current one is too big. I'll upload one later if needed.

### Issue description

When you use a Tiara and are already toggled into sprint mode, the dashing happens every 2 seconds. This makes it very hard to control your flight as I always end up dashing past where I want to stop. It also seems to contradict the manual, which says dashes happen when you press Ctrl while not sprinting.

### Steps to reproduce

1. Toggle sprinting on
2. Fly forward while wearing tiara
3. Notice that dashes keep happening every 2 seconds

**Comment by williewillus** [comment] 2022-10-22 22:32
I can't reproduce this is in 1.19 dev, and #3108 seems to imply this was already fixed 2 years ago. Can you try on some other versions (1.17, 1.18) to help with some details?

**Comment by anoomolu** [comment] 2023-11-23 10:13
Closing this as I'm unable to reproduce with Botania 1.16.5-440.2/3 + deps, 1.18.2 or 1.19.2.

**Closed as not planned by anoomolu** 2023-11-23 10:13 UTC
