### ISSUE TITLE
[1.16.1] Lexica Botania crash upon opening the book.

### ISSUE THREAD

**Issue by LadyAerlevsedi** [Vazkii/Botania#3390] opened 2020-08-10 20:23 UTC
# Version Information
Forge version:  1.16.1-forge-32.0.108
Botania version:  Botania-1.16-399

# Further Information
https://pastebin.com/hW35JTjR

What I expected to happen:
Open the book and see the contents
What happened instead:
Crashed, with an error telling me the failure occurred upon render.

Not entirely sure why it happened. My programming knowledge is limited and in C#, not Java but I had a look at it and came up blank so I figured best leave it to you folks to see if the issue is more clear to someone with experience in the language.

**Comment by LadyAerlevsedi** [comment] 2020-08-10 20:48
Noticed removing Optifine appears to allow it to run correctly, so it may be a conflict there somehow.

**Comment by Hubry** [comment] 2020-08-10 22:41
Duplicate of #3387, remove optifine or downgrade forge to build 106

**Closed by Hubry** 2020-08-10 22:41 UTC
