### ISSUE TITLE
Pasture, boreal, infestation etc. seeds not working on floating flowers.

### ISSUE THREAD

**Issue by Chessboii** [Vazkii/Botania#4541] opened 2024-01-12 21:11 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-443

### Modloader version

Forge 47.2.0

### The latest.log file

N/A

### Issue description

An issue I found is the inability to add any types of seeds to floating flowers to modulate delay. I try right-clicking and it simply doesn't work. When I go on older versions of Botania all of my floating flowers that had a delay from seeds became normal floating flowers. I removed all other mods I had installed (besides curios and patchouli), but the error was still present.

**Comment by anoomolu** [comment] 2024-01-12 21:39
Hi, thanks for the bug report. This has been confirmed and is a duplicate of #3892, so I'm gonna close this.

**Closed as not planned by anoomolu** 2024-01-12 21:39 UTC
