### ISSUE TITLE
Dandelifeon not working with enchanted soil (Growth Seed)

### ISSUE THREAD

**Issue by Danoned** [Vazkii/Botania#4513] opened 2023-12-10 22:15 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

1.20.1-forge-47.2.0

### Modpack info

vanilla + botania

### The latest.log file

n/a

### Issue description

Dandelifeon Game of Life mechanic doesn't gets boosted by 2x enchanted soil after the update from 1.19.2-440 to 1.20.1-441

I tested it in 2 worlds created before 1.20.1 and a world created in the 1.20.1 and it wont work.

### Steps to reproduce

1. Test a dandelifeon setup with enchanted soil (it will not work)
2. Test the same dandelifeon setup without the enchanted soil (it will be the same speed)
3. Test any other plant setup with enchanted soil (it will work)

**Comment by anoomolu** [comment] 2023-12-10 23:05
Closing as this is a duplicate of #4405.

**Closed as not planned by anoomolu** 2023-12-10 23:05 UTC
