### ISSUE TITLE
[1.16.5Forge] Crash Report

### ISSUE THREAD

**Issue by Curtainz** [Vazkii/Botania#3766] opened 2021-07-03 02:25 UTC
[crash-2021-07-03_10.03.12-fml.txt](https://github.com/Vazkii/Botania/files/6757713/crash-2021-07-03_10.03.12-fml.txt)

I can run these mods on the client side, but they can't run on the server side.
I used the same version of the forge(36.1.32).

**Comment by Curtainz** [comment] 2021-07-03 02:28
Botania Version: Botania-1.16.5-417
Forge Version: 36.1.32

**Comment by Hubry** [comment] 2021-07-03 09:22
Update to build 418

Duplicate of #3764.

**Closed by Hubry** 2021-07-03 09:22 UTC
