### ISSUE TITLE
Flowers disappearing from flower pouch

### ISSUE THREAD

**Issue by Adam-Kay** [Vazkii/Botania#2709] opened 2018-08-22 10:58 UTC
# Version Information
Forge version:  forge-14.23.4.2757
Botania version:  botania r1.10-354.jar

# Further Information
Link to crash log: N/A

Steps to reproduce:
1.  Open Flower Pouch
2. Insert flowers into flower pouch
3. Open another inventory GUI. So far the Creative inventory or opening a backpack manage to trigger this effect
4. Close the other GUI and open the flower pouch once more

What I expected to happen: The flower pouch should have as many flowers as I put in.

What happened instead: All the flowers are erased from the flower pouch and all the counters display a red “0”

**Comment by williewillus** [comment] 2018-08-22 19:36
I can't get this  to happen, are you on a server?

**Comment by exube** [comment] 2018-08-23 01:02
It seems to only happen on servers.  Even then, it doesn't happen all the time. It may be more common with more flowers in the bag.  It also happens to the bauble box.

**Comment by williewillus** [comment] 2018-08-23 05:57
does it only happen in creative mode? that has known issues in forge with deleting item capabilities (the thing that stores inventories)

**Comment by netmc** [comment] 2018-10-11 23:55
I just noticed this happened to me today as well.  Went to go make some stuff, and all my flowers are gone.  I have died a few times since I last used my flower pouch, so not entirely sure if this was the gravestone mod dropping the data or just the flowers randomly disappearing.  I am running my own server.  I will see if I can identify the cause.

**Comment by SapphireIceQueen** [comment] 2018-12-01 09:29
Same thing here, I'm not sure what is causing it but I'm also on a server. I was using my flowers for their petals but I know I didnt use them all. i was only using black and brown and I had some purple. Everything is gone.

**Comment by DoomRater** [comment] 2019-08-07 19:14
Potentially related to the issues with Forge described in #2408?  One of my players also reported this happening to her Bauble case and Flower Pouch and she has switched to using Backpacks to store the items to ensure it doesn't keep happening.

**Comment by macks2008** [comment] 2019-10-21 12:14
I just noticed this happened to me as well, though in my case I'm not sure what triggered it. It was on a Forge + spongeforge server (is anyone else using sponge?), and although I might have used creative mode at some point, I don't think it was reason enough to explain my pouch's data being cleared. Why does this only seems to happen with flower pouches and bauble cases from this mod? Does no one else implement capability NBT for their metadata? If they do, might checking what they do differently... In the meantime, I'm switching to /Dank/Null for my floral storage needs.

**Comment by DoomRater** [comment] 2019-10-21 12:52
I am not using Sponge.  Also, Immersive Engineering Toolboxes are confirmed affected by an underlying Forge issue, which Forge says is a vanilla Minecraft issue.  Backpacks! definitely does not seem affected by these issues though, and I have no clue how its storing inventory contents.  It's not in NBT data- all that's there is a UUID.

**Comment by Sourceshard** [comment] 2019-12-25 02:39
Sorry to revive this post but was curious. Is this fix something we can hope to see for previous versions? 1.12.2  Specifically?

**Comment by Brycey92** [comment] 2020-04-14 18:04
I believe this and #1894 are the same issue. I'm also having this problem in 1.12.2, with creative, Thermal Expansion satchels, and inventory sorting, and would absolutely love a backport for the fix.

**Comment by williewillus** [comment] 2020-04-14 19:03
Duplicate of #1894

**Closed by williewillus** 2020-04-14 19:03 UTC
