### ISSUE TITLE
Pixie Spawn Chance Crash - Server Crash When Take Damage

### ISSUE THREAD

**Issue by doxne** [Vazkii/Botania#4493] opened 2023-11-27 19:02 UTC
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

Botania-1.16.5-420.2

### Modloader version

Mohist: Forge 36.2.39

### The latest.log file

Link to crash log and latest log: https://gist.github.com/doxne/ad337ab110d71d864f3ad1d2395d520f

### Issue description

The game crashes when I have botania installed and take damage from any enemy.

### Steps to reproduce

1- Receive damage from a mob.
2- The game crashes.
What I expected to happen:
Losing HP after taking damage.
What happened instead:
The game crashed.

### Other information

There are other similar reports, but the solution for them doesn't work for me, in fact I don't have the mod that caused the incompatibility for them:
Crash when killing a mob #3201
Server Crash when take damage #3382
Pixie Spawn Chance Crash #3517

**Comment by anoomolu** [comment] 2023-11-27 22:34
Duplicate of https://github.com/VazkiiMods/Botania/issues/4445.

**Closed as not planned by anoomolu** 2023-11-27 22:34 UTC

**Comment by doxne** [comment] 2023-11-27 22:38
I found the solution, the Pufferfish's Skills mod causes an incompatibility with botania, the solution is to delete the botania mod or the Pufferfish's Skills mod.
