### ISSUE TITLE
Shard of laputa upgrade recipe broken

### ISSUE THREAD

**Issue by neochiken** [Vazkii/Botania#3234] opened 2020-04-07 02:18 UTC
The recipe for upgrading a shard of laputa from power 1 to power 2 isnt working even though JEI can display it. furthermore through creative I was able to spawn in a level 2 and upgrade it to XX but the recipe for XX to XXI breaks again.
# Version Information
Forge version:  28.2.3
Botania version:  Botania r1.11-378.jar

# Further Information
This is part of the Enigmatica 4 modpack v0.5.1 but was also experience in v0.4.5 and v0.4.10

What I expected to happen:
upgrade shard of laputa

What happened instead:
empty result box

**Comment by Hubry** [comment] 2020-04-07 10:13
Duplicate of #3107, update Botania. (Also lvl XXI is not supposed to be craftable)

**Comment by Hubry** [comment] 2020-04-07 10:20
Looks like I was a bit too fast to close, and creative pulled shards actually work just fine...

**Closed** 2020-04-15 21:00 UTC

**Comment by GordonHollow** [comment] 2020-05-05 05:08
Also have this issue, still not fixed in 1.14.4
