### ISSUE TITLE
Armour Malfunction

### ISSUE THREAD

**Issue by Shinigami-Apples** [Vazkii/Botania#2873] opened 2019-03-14 20:30 UTC
# Version Information
Forge version:  14.23.5.2815
Botania version:  +r1.10-360
- Playing on a multiplayer server, if that is of any help. There were no crashes, this is just a visual bug.

![Legs Malfunction](https://user-images.githubusercontent.com/40737747/54389019-0afefd80-4697-11e9-829d-65333562aa10.png)

Hi. Basically, as seen in the screenshot above, wearing any Botania armour (with the exception of the Manaweave Robe) and sneaking creates this very odd visual bug. The legs of the armour stay on the player, but a copy of the top of the legs juts out behind them. I'm not sure if this is intentional as a visual effect, but I thought I would bring it to your attention.

**Comment by Hubry** [comment] 2019-03-14 23:01
Duplicate of #2581.

**Comment by williewillus** [comment] 2019-03-15 02:37
^

**Closed by williewillus** 2019-03-15 02:37 UTC
