### ISSUE TITLE
Mana pool sync

### ISSUE THREAD

**Issue by Bellwar** [Vazkii/Botania#988] opened 2015-05-17 17:02 UTC
I have problems with manapools to not update.

Mostly when sparks are use and even more when augment is on them.
You can fix it just by right-click.

I dont know if you know about this problem but if you want i can record it so you can see it better.

**Comment by Vazkii** [comment] 2015-05-17 17:10
Please read the [contributing guidelines](https://github.com/Vazkii/Botania/blob/master/contributing.md) before posting an issue. Your issue is either missing critical information or going against one of the guidelines there stipulated.
I'm closing this issue until it's rectified to follow the guidelines. You can comment on closed issues.
*This message is a macro.*

**Comment by Bellwar** [comment] 2015-05-17 17:32
Im playing on DW 1.3.1 pack and I have problem with manapools not updating. (its for long time).
I have manapool with dominant spark on it. Other sparks are giving it mana (lot of mana) but even then the manapool is empty and you cant even see it, only after relog or rightclick, it update its contain and you cann see some mana inside the manapool.

i think its bug because mana spreader doesnt have this problem.
I hope i write it good this time. ^^

**Comment by MrKunji** [comment] 2015-05-17 17:34
You still haven't specified the version of Botania you are using.

**Comment by Bellwar** [comment] 2015-05-17 17:35
I think its r1.6-184 what i can read on FTB changelog.

**Comment by MrKunji** [comment] 2015-05-17 17:36
Update to 189.

**Comment by Bellwar** [comment] 2015-05-17 17:37
I dont see it fixed but i will try.

**Comment by Bellwar** [comment] 2015-05-17 17:46
Ok still same problem.

**Comment by Vazkii** [comment] 2015-05-17 17:58
Does this happen in singleplayer or multiplayer?

**Comment by Bellwar** [comment] 2015-05-17 18:00
Singleplayer but i think same in multiplayer.

**Comment by Bellwar** [comment] 2015-05-17 18:01
I think i ran into this problem from when sparks was in and i still can find this problem

**Comment by Lazersmoke** [comment] 2015-05-17 20:07
If it helps, my reimplementation of mana pools in my addon still have this issue, so it can't be something specifically targeting TilePool, as my class extends TileMod not TilePool. https://github.com/Lazersmoke/Botanical-Workshop/blob/master/src/main/java/lazersmoke/botanicalworkshop/common/block/tile/mana/TileElvenPool.java

**Comment by Vazkii** [comment] 2015-05-18 14:22
I can't reproduce this.

**Closed by Vazkii** 2015-05-18 14:22 UTC
Labels: investigate

**Comment by Lazersmoke** [comment] 2015-05-20 12:20
@Vazkii I could be wrong, but there aren't any worldObj.isRemote checks in the spark, so mana adding and removing will occur both on the client and the server, much like the fake cows from before. A better solution maybe to add a check to tile pool.recieve mana() rather than to every call there of.
