### ISSUE TITLE
Issues With Botania Shears

### ISSUE THREAD

**Issue by theboo** [Vazkii/Botania#3263] opened 2020-04-23 17:13 UTC
# Version Information
Forge version: 31.1.47 
Botania version:  r1.15-382

Steps to reproduce:
1. Break tall mystical flowers with elementium or manasteel shears
2. Break leaves with elementium or manasteel shears

What I expected to happen: Tall flowers to drop the flower and leaves to drop their respective leaves block

What happened instead: Tall flowers do not drop tall flowers when broken with botania shears. Leaves to not drop leaves blocks when broken with botania shears(both drop nothing)

The botania shears do work on sheep. And Vanilla shears do work on botania tall mystical flowers.

**Comment by williewillus** [comment] 2020-04-23 17:15
duplicate of #3262 
fixed in next update

**Closed by williewillus** 2020-04-23 17:15 UTC

**Comment by theboo** [comment] 2020-04-23 17:18
man, i searched "shears" before posting too, haha, looks like it was misspelled in that issue title :D carry on
