### ISSUE TITLE
crashes when  piston pushed a redstone torch

### ISSUE THREAD

**Issue by ShadowSTARS616** [Vazkii/Botania#4536] opened 2024-01-04 13:49 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-442

### Modloader version

Forge:47.2.19

### The latest.log file

https://gist.github.com/ShadowSTARS616/028224c4ac8f75c46fc538bcab72713f

### Issue description

Game crashes when using a piston to push a redstone torch; this world can not be loaded again

### Steps to reproduce

1. place a piston
2. place a redstone torch in front of the piston
3. place a lever behind the piston
4. Pull! and the game crashes
5. if using server, when load this world again, it will crash after done

**Comment by artemisSystem** [comment] 2024-01-04 14:05
duplicate of #4527, please update to 443 which fixes this crash

**Closed as not planned** 2024-01-04 14:05 UTC
