### ISSUE TITLE
Make punching 2-high mystical flowers give a normal flower?

### ISSUE THREAD

**Issue by abculatter2** [Vazkii/Botania#2265] opened 2017-05-24 10:01 UTC
Mainly just to help with the 'wtf!?' moment in the start of the game for new players.

**Comment by Nincodedo** [comment] 2017-05-24 15:14
Duplicate of #1769

**Comment by williewillus** [comment] 2017-05-28 21:21
^
but I'm wondering if there's a reason for it to be like that anymore. iirc it was disabled due to technical issues back then

**Comment by Hubry** [comment] 2017-05-28 23:48
Wasn't that because of inventory clutter? Which would make more sense, seeing how much clutter the normal flowers can be already (flower pouches are nice).

**Comment by williewillus** [comment] 2017-06-08 23:57
Okay then we'll stick with it then (this is a dupe anyway)

**Closed by williewillus** 2017-06-08 23:57 UTC
