### ISSUE TITLE
Undefined flower when flower is placed using wand

### ISSUE THREAD

**Issue by Jackattacksonz** [Vazkii/Botania#2697] opened 2018-08-12 21:12 UTC
Version r1.9-341 of Botania
Version 1.10.2 of Minecraft
I was playing on the SkyFactory 3 modpack by Bacon_Doughnut when i came across this texture bug. I used the Unbreakable Wand from the mod Better Builder's Wands, which allows an area of the same type of block to be placed at once as long as it is already in your inventory. The item shows a highlight of where the blocks will be placed based on the build setting and the number of blocks of the same type. I saw that when i used it to hover over an Endoflame it produced the highlight, I right clicked to see what would happen and it placed a Thermalily from my inventory as an undefined block.
Thank you, JackAttacksonz.

**Comment by Hubry** [comment] 2018-08-17 18:03
Duplicate of #2587. Also, try to reproduce this in 1.12.2 running latest versions of mods as 1.10 is no longer supported.

**Comment by williewillus** [comment] 2019-08-29 00:54
dupe as mentioned above, issue on bbw's side
(this will also be resolved in 1.14+ as a result of unrelated changes)

**Closed by williewillus** 2019-08-29 00:54 UTC
