### ISSUE TITLE
Misc Flower back from Flower Pot

### ISSUE THREAD

**Issue by Ra-Zim** [Vazkii/Botania#2892] opened 2019-04-18 08:41 UTC
# Version Information
Forge version:  MC 1.12.2, Forge 14.23.5.2825
Botania version:  r1.10-361

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
No crash, I just got a Misc Flower and the mod told me to report it. I put a Hydroangeus into a flower pot, first one from the mod Quark, then a vanilla flower pot, for decoration. It was just a green stem so I right clicked to pull it out and got the Misc Flower back.

**Comment by quat1024** [comment] 2019-04-28 07:18
Dupe of https://github.com/Vazkii/Botania/issues/2735 !

This is on Quark's end. You can blacklist flowers in the config file (it uses the same list as the Colored Flower Pots option, even if it's disabled btw)

**Closed** 2019-04-29 04:27 UTC
