### ISSUE TITLE
Tall Mystical Flowers drop without shears

### ISSUE THREAD

**Issue by Acuzikwastaken** [Vazkii/Botania#3148] opened 2020-01-17 22:43 UTC
Forge version:  28.1.109
Botania version:  374th Edition

Attempted to break tall mystical flowers by hand without shears

What I expected to happen: The flower to break and not drop anything

What happened instead: The flower broke and dropped like normal

**Comment by Hubry** [comment] 2020-01-17 23:30
Duplicate of #3008

**Closed by Hubry** 2020-01-17 23:30 UTC
