### ISSUE TITLE
Thermalily with Ritual bloodmagic

### ISSUE THREAD

**Issue by nailfor** [Vazkii/Botania#1821] opened 2016-02-29 11:37 UTC
After the last update I found Thermalily quickly empties the source of lava .
I create this source by ritual Serenade of the Nether, flowers drain blood from LP 2k-3k/sec, and the speed was previously 20LP/s(average, flowers long rest)
As a result, a network of 4 hours where the devastated 40 million LP

**Comment by AlterAkima** [comment] 2016-02-29 11:40
https://github.com/Vazkii/Botania/issues/1812
Close it.

**Comment by TheWhiteWolves** [comment] 2016-02-29 11:41
Intended Behaviour

**Closed by TheWhiteWolves** 2016-02-29 11:41 UTC

**Comment by nailfor** [comment] 2016-02-29 12:12
That is how it should be?

**Comment by yrsegal** [comment] 2016-02-29 12:46
yes.

**Comment by bookerthegeek** [comment] 2016-02-29 15:44
Please read read you lexicon.

**Comment by nailfor** [comment] 2016-03-01 06:05
"The Thermalily acts as a Lava counterpart to the Hydroangeas. As expected, the flower will absorb Lava around it, in the same height as it, to create Mana.
After absorbing the Lava, the flower will produce Mana for around 45 seconds. After it stops, it needs a bit of time, around 5 minutes, to cool down, before it can absorb more Lava.
The amount of Mana the Thermalily produces during its active period is extremely high, serving as a very functional flower for when a quick boost is needed.
During the "cooldown" period, if the flower were to absorb any Lava, it instead consumes it, generating no Mana and having to wait 5 minutes from there to start over.
While placing Lava in the world is definitely possible via Dispensers, automatically gathering it and carrying it from the Nether or deep underground is another story entirely.
As such, the Thermalily is clasified as a "semi-automatable" flower."

Nothing is said about the fact that in the period of cooldown flower consuming  lava

**Comment by JRoffel** [comment] 2016-03-01 06:24
"During the "cooldown" period, if the flower were to absorb any lava, generating no mana..."

Sent from my iPhone

On 1 mrt. 2016, at 07:06, nailfor <notifications@github.com<mailto:notifications@github.com>> wrote:


"The Thermalily acts as a Lava counterpart to the Hydroangeas. As expected, the flower will absorb Lava around it, in the same height as it, to create Mana.
After absorbing the Lava, the flower will produce Mana for around 45 seconds. After it stops, it needs a bit of time, around 5 minutes, to cool down, before it can absorb more Lava.
The amount of Mana the Thermalily produces during its active period is extremely high, serving as a very functional flower for when a quick boost is needed.
During the "cooldown" period, if the flower were to absorb any Lava, it instead consumes it, generating no Mana and having to wait 5 minutes from there to start over.
While placing Lava in the world is definitely possible via Dispensers, automatically gathering it and carrying it from the Nether or deep underground is another story entirely.
As such, the Thermalily is clasified as a "semi-automatable" flower."

Nothing is said about the fact that in the period of cooldown flower consuming lava

-

**Comment by nailfor** [comment] 2016-03-01 06:45
It is not clearly written. I think word "if" excess

**Comment by williewillus** [comment] 2016-03-01 06:52
This thread is not for debating the grammar of the lexicon entry, which I find to be plenty sufficient.

Lock pls :P
