### ISSUE TITLE
Rafflowsias Not Eating All Flowers?

### ISSUE THREAD

**Issue by abculatter2** [Vazkii/Botania#2193] opened 2017-03-11 00:53 UTC
(Using v1.9-342)

In the Lexica Botania, the entry for the Rafflowsia seems to imply that it should be able to eat all apothecary flowers. However, it only seems capable of eating mana generating flowers. Is this a bug, or a feature? If it's not a bug, then it seems to make the Rafflowsia pretty much useless since the only flowers that are worth feeding it is the Hydroangea and the Endoflame.

**Comment by williewillus** [comment] 2017-03-11 02:07
dupe of #2054

**Closed by williewillus** 2017-03-11 02:07 UTC
