### ISSUE TITLE
Mana spreader accumulating thousands of mana blasts inside itself, causing major server lag.

### ISSUE THREAD

**Issue by ViciousVinnyD** [Vazkii/Botania#1599] opened 2015-11-30 14:52 UTC
Something strange happened with one of the mana spreaders on my DireWolf20 1.8.0 server.
Something caused a single mana spreader to accumulate tens of thousands of mana blasts inside itself, causing massive server lag.
![manaburst](https://cloud.githubusercontent.com/assets/10350888/11474691/86febd2c-9771-11e5-990c-daee6b7b8abf.png)
Unfortunately I was unable to take a look at the mana spreader itself as anyone who approached it would immidiately time out, so I just deleted the chunk and called it a day.
I have a copy of this area if you want to take a look at it.

**Comment by bookerthegeek** [comment] 2015-11-30 21:42
Was the target for the spreader removed?

**Comment by ViciousVinnyD** [comment] 2015-11-30 23:11
No way of checking, but I'd assume that's what happened. Either way mana blasts should not be allowed to stack up like that.

**Comment by bookerthegeek** [comment] 2015-12-01 01:27
Should not... but does.

I believe we solved this on our server by removing the spreader if it does not have a valid target. Was annoying to users at first but they learned to deal.

Just make sure to tool tip the spreaders to inform otherwise you get many angry people.

**Comment by bookerthegeek** [comment] 2015-12-01 01:28
We tried just a periodic clearing of the entity of the mana burst but that caused the spreaders to become unbound from their targets.

I guess the potential lose was better then having to remind everything every couple hours.

**Comment by MrPotatoGaming** [comment] 2015-12-30 05:03
Do either/both of you happen to be using Cauldron or some other Bukkit/Forge compound? If so, it's probably related to this. This issue doesn't happen in any vanilla/forge server I've used. (Currently playing on one as of right now.) The issue was/is related to the way Cauldron handled chunk unloading, similar issue happened to me. The only real clear way to solve this is either forced-mana-bolt de-spawn or not chunk loading. (The issue stemmed from force-chunk load with chunk loaders.) It also happened with some other magic's mod bazooka thing. Can't remember if it was Ars Magicka or Bloodmagicka. Can't say I've played with either of the mods. 

An hourly /cofh kill botania. whatever should fix the problem server side. 

If it isn't Bukkit/Forge related, sorry for the useless input.

**Comment by bookerthegeek** [comment] 2016-01-03 06:09
Ours is kcauldron. 

//rant start
And I do understand the thought process behind modders refusing to support It. Although I am curious to know if anybody actually runs a large player based multi-pack Minecraft network only on forge? Not to my knowledge. Sad to say that most if every of the top 10 Minecraft networks do not use a pure forge environment. But before you go blame kcauldron/Bukkit/Cauldron, please go actually look into the code for it. Just because you don't understand it does not mean that it is the cause. Maybe it is just point out a fault in the mods code.
//rant over

**Comment by MrPotatoGaming** [comment] 2016-01-03 18:30
Okay, but here's the thing: if you can't reproduce the issue in a forge situation, it's a KCauldron bug. Furthermore, the reason a good chunk of of developers don't support Bukkit/Forge projects is because Bukkit is dead. Yes, I miss the glory days of Bukkit, it's a very nice server utility. Plus, for large scale servers, lets face it, it handles better than forge. I've had servers go from 50 ms per tick to 15 ms per tick simply by using Cauldron. That being said, you can't just go "look at the code" for a project that received a DCMA. The project is locked up, closed away, and anything that derives off the code is in legal gray zone.  

Now, that being said "Sponge" is beautiful. Spogne is the new "Bukkit/Forge." It has developed from the ground up to be built on top of forge. That's very important for compatibility and stability. It is finally released to Beta and you should be using that instead. I can't tell you if Sponge is stable, I don't use it.

**Comment by Katrix-** [comment] 2016-01-05 13:44
Alright I'll just comment here as well. I've seen this happening on my own server too recently which is NOT using any custom version of forge. I am using Fastcraft however, anyone else using that. I should however note that both the Forge and the Botania version in this pack is quite old, although I'm going to update soon. This at least shows that this isn't Cauldron's fault or anything like that.

**Comment by JRoffel** [comment] 2016-01-05 14:55
@Katrix- unless it was fixed in a more recent version of botania and/or forge, and it now IS a problem with cauldron... You cannot rule things out if you're comparing with different data... It doesn't work like that

**Closed** 2016-09-09 22:43 UTC
Labels: investigate
