### ISSUE TITLE
[1.16.1] Crash spreading mana with mana spreader to mana pool

### ISSUE THREAD

**Issue by Sebulba13** [Vazkii/Botania#3400] opened 2020-08-13 11:23 UTC
# Version Information
Forge version:  1.16.1-forge-32.0.108
Botania version:  Botnia-1.16-401

# Further Information
Link to crash log: https://gist.github.com/Sebulba13/5a3f1031b12d29fb5b2eefdac4e4d77b
Steps to reproduce:
1. place mana spreader
2. place mana pool
3. place mana generator
4. connect all stuff
5. wait until mana starts spreading

What I expected to happen: mana to appear in mana pool

What happened instead: game crashed

**Comment by Hubry** [comment] 2020-08-13 11:24
Duplicate of #3397, downgrade Forge

**Closed by Hubry** 2020-08-13 11:24 UTC
