### ISSUE TITLE
Abstruse platform loses its appearance after restart server

### ISSUE THREAD

**Issue by ArtemMASTER** [Vazkii/Botania#4623] opened 2024-05-02 10:41 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-444-FORGE-SNAPSHOT

### Modloader version

Forge 47.2.1

### The latest.log file

none

### Issue description

The abstruse platform from Botania can be disguised as another block, but after restarting the server, this “disguise” disappears and the abstruse platform becomes standard.

### Steps to reproduce

1. Install a abstruse platform
2. Take any block
3. Right-click the block on the platform.
4. wait for restart

### Other information

'botania:abstruse_platform'

**Comment by TheRealWormbo** [comment] 2024-05-02 16:24
Duplicate of #4603. A fix is in the pipeline, but no ETA on release yet.

**Closed as not planned by TheRealWormbo** 2024-05-02 16:24 UTC
