### ISSUE TITLE
a glitch with The 1.12.2 Pack: Perfectly Complex

### ISSUE THREAD

**Issue by ThePugZ** [Vazkii/Botania#3169] opened 2020-02-08 21:29 UTC
# Version Information
Forge version:  1.12.2
Botania version:  r1.10-363

# Further Information
Link to crash log: https://paste.dimdev.org/rujuxulome.mccrash
Steps to reproduce: 
1. First step: attempted to load into server i play on
2. Second step: it crashes and say's botania is the issue

What I expected to happen: load just fine

What happened instead: it didn't load at all

Note: i was taking a potal to the mining dimention where i had set up my botania stuff, but upon entry my game crashed saying botania was the cause, and after attempting to rejoin, it kept crashing

**Comment by Hubry** [comment] 2020-02-08 23:30
Duplicate of #2205

Replace VoxelMap with JourneyMap, or Xaero's Minimap + Worldmap.

**Closed by Hubry** 2020-02-08 23:30 UTC
