### ISSUE TITLE
Crash while attacking a Creeper with Excaliber

### ISSUE THREAD

**Issue by TennePG** [Vazkii/Botania#716] opened 2015-04-02 19:47 UTC
Crashlog: http://pastebin.com/PgYPZ8VA

Forge Version: 10.13.2.1343-1.7.10

Mods: 
Baubles - 1.7.10 - 1.0.1.10
Botania - r1.6 - 173

EDIT: In the crashlog, I noticed that there was an error that seems to me like a dependency on CodeChicken Lib (java.lang.NoClassDefFoundError: codechicken/lib/vec/Vector3), but then again, I'm not a coder, nor do I know anything about Java ¯\_(ツ)_/¯

**Comment by MrKunji** [comment] 2015-04-02 19:58
The sword use classes from CodeChicken Core., install it.

**Comment by TennePG** [comment] 2015-04-02 19:58
I just did, actually. I just tested it to see if it did use classes from it, and it did.

**Comment by Vazkii** [comment] 2015-04-02 20:15
Dupe of #705

**Closed by Vazkii** 2015-04-02 20:15 UTC
