### ISSUE TITLE
[1.12.2] Most recently placed flower does not render properly

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#2452] opened 2017-11-30 20:02 UTC
Forge version: 2555
Botania version: 350
Link to crash log: N/A

Steps to reproduce:
1. Get some Pure Daisies
2: Place them down one at a time

What I expected to happen:
The flowers to render properly from the start.

What happened instead:
The Flower renders as a checkered purple and black block, with the hitbox of the flower. When I place a second flower, it also renders incorrectly, but the first flower is then fine.

After placing the first flower:
![2017-11-30_11 57 29](https://user-images.githubusercontent.com/6917535/33452192-47a5ceb4-d5c6-11e7-8eb0-234a2d9cd585.png)
After placing the second flower (note that the first is now rendering properly):
![2017-11-30_11 57 36](https://user-images.githubusercontent.com/6917535/33452193-47c11dcc-d5c6-11e7-9496-bfe8b931fa19.png)

Forcing a re-render does not fix it.

**Comment by Zsashas** [comment] 2017-11-30 20:05
Followup: After breaking and re-placing both a few times, they now both refuse to render at all, regardless of order.

**Comment by williewillus** [comment] 2017-11-30 20:25
can you do it with botania alone?

**Comment by razage** [comment] 2017-12-09 21:51
I can't speak to his setup, but I have the same issue. It seems to be caused by [Fancy Block Particles](https://minecraft.curseforge.com/projects/fancy-block-particles). Disabling it fixed the issue.

**Comment by Zsashas** [comment] 2017-12-09 22:27
Ohhhh that's the mod that does that. Couldn't remember what mod was making everything 3d but it was fun so I just left it. That makes sense, though.

**Comment by williewillus** [comment] 2017-12-10 01:52
It's because the flower needs data from the tile entity to render properly. How does this mod handle something like the colored beds or banners, which need the same?

**Comment by razage** [comment] 2017-12-10 03:15
I can't speak to the technical side of things (which is probably what you need admittedly), but I just tested it and the beds and banners work as intended.
![example](https://user-images.githubusercontent.com/9331220/33801617-06ca0af6-dd26-11e7-85a8-b7f17329d155.png)

**Comment by razage** [comment] 2017-12-10 03:22
Follow up: Don't know if this helps, but I noticed the beds/banners use metadata/damage values (minecraft:bed:1) and the pure daisy uses a tag (botania:specialflower.withTag({type:"puredaisy"}))

**Comment by williewillus** [comment] 2017-12-10 05:52
banners with custom patterns use NBT though

**Comment by Zsashas** [comment] 2017-12-10 06:27
I only see unpatterned banners in that image. It might be that each color base banner is a fallback, which botania flowers do not have. Then again i could be entirely off the mark.

**Comment by razage** [comment] 2017-12-10 08:42
New to 1.12, didn't know about that. But I had also been posting an issue on Mekanism's repo because of a crash caused by placing tanks and pipes. Turns out FBP caused that too. So I'm guessing it's a problem on their end with placed blocks not having nbt data or something like that.

**Comment by williewillus** [comment] 2017-12-17 22:04
closing as it's not a botania issue.

basically, the model needs an ExtendedBlockState to work properly, which itself needs the TE to have the subtile information set

**Closed by williewillus** 2017-12-17 22:04 UTC
