### ISSUE TITLE
Shard of Laputa fails to transport certain blocks

### ISSUE THREAD

**Issue by Peach774** [Vazkii/Botania#4037] opened 2022-05-12 04:01 UTC
### Mod Loader

Forge

### Minecraft Version

1.18.2

### Botania version

1.18.2-431

### Modloader version

Forge 40.1.19

### The latest.log file

https://gist.github.com/Peach774/2f6df6a4011aa946b271d0e76c9f07fc

### Issue description

The shard of Laputa doesnt correctly transport water or tall grass. Tall grass only has the top half and for water, only waterlogged blocks are transported and they often break as part of transport.

![image](https://user-images.githubusercontent.com/5171184/167989173-41626f19-6b99-457c-8ec2-a5a35b8f7219.png)
![image](https://user-images.githubusercontent.com/5171184/167989200-f5a8a324-e600-40b6-abd1-7070c8608cfd.png)

### Steps to reproduce

1. Use a Shard of Laputa on an area with tall grass or on an ocean bed
2. Profit

**Comment by williewillus** [comment] 2022-05-12 04:36
Duplicate of #2128 

It's hard to handle in a general manner.

**Closed as completed by williewillus** 2022-05-12 04:36 UTC
