### ISSUE TITLE
ManaSpreaders causing chunk loading?

### ISSUE THREAD

**Issue by ruifung** [Vazkii/Botania#408] opened 2014-12-05 23:11 UTC
When my base is only partially chunkload, the onChunkLoad seems to be caused by the TileSpreader class, which in returns cause a significant performance overhead when combined with mekanism as mekanism refreshes its transmitters network on chunk load. (And by performance overhead it appears to lock up the server thread often.) After placing a world anchor down, this no longer happens, confirming my suspicion its rapid chunk loading/unloading which was causing the lockups.

I'm not sure where to put this issue, this is a snapshot from the profiler. https://dl.dropboxusercontent.com/u/23843338/botania-mek.nps

**Comment by kevinkjt2000** [comment] 2015-01-06 18:34
This may be related to the weird warning I have been seeing on my server.
I see stuff like this quite often:
06.01 12:29:07 [Server] Server thread/WARN Wrong location! EntityManaBurst['Mana Burst'/8669, l='world', x=-973695.63, y=107.50, z=-1703.50] (at -60856, -107 instead of -72, -107)

I have also noticed that when mana pools are full the entity count in the area can go way high.  After emptying some of the mana the entity count goes back down to normal.  My guess is that all the ManaBurst entities are colliding really hard and scattering to the ends of the earth.  I do not know if this is related or not, but mekanism is also in the pack I use.

**Comment by CandiceJoy** [comment] 2015-01-26 19:21
Same problem here.  Nothing but botania stuff and a couple meka cables not hooked up to anything.  When the chunks are chunkloaded everything is fine, but when the chunks aren't chunkloaded and nobody is around, the server lags to heck.  :/  We also see a rather strangely high number of mana bursts given that nobody on the server has much of a botania setup, yet it's still not uncommon to have 2000 or so.  The problem is exacerbated by the fact that ChickenChunks chunkloaders seem to randomly stopped working even though the config is set to allow them to run at all times.  We've had to resort to railcraft admin loaders, but it fixes the problem right up.

**Comment by Vazkii** [comment] 2015-04-17 11:30
Does it still happen with the chunk checking changes in the latest version?

**Comment by kevinkjt2000** [comment] 2015-04-25 05:19
I updated to the latest version.  For the next few days, I will monitor the logs to see if the warning still appears.

**Comment by Vazkii** [comment] 2015-04-29 16:31
Any updates?

**Comment by kevinkjt2000** [comment] 2015-04-30 05:32
The only warnings that I see now are printed just before the server is done loading the world:
[10:19:05] [Server thread/WARN]: Wrong location! EntityManaBurst['Mana Burst'/51, l='world', x=-1150.50, y=13450.99, z=-135213.61] (at -72, -8451 instead of -72, -106)
[10:19:05] [Server thread/WARN]: Wrong location! EntityManaBurst['Mana Burst'/52, l='world', x=8349539.53, y=-231329.33, z=-1703.50] (at 521846, -107 instead of -72, -107)
[10:19:05] [Server thread/WARN]: Wrong location! EntityManaBurst['Mana Burst'/53, l='world', x=-973695.63, y=107.50, z=-1703.50] (at -60856, -107 instead of -72, -107)
[10:19:05] [Server thread/INFO]: Preparing start region for level 0
[10:19:06] [Server thread/INFO]: Done (3.421s)! For help, type "help" or "?"

**Comment by kevinkjt2000** [comment] 2015-04-30 05:35
I forgot to mention that I see those messages at the start consistently, but not every time.  I have several logs that I could post as gists if you think they would be helpful.

**Comment by Vazkii** [comment] 2015-04-30 12:13
I have no idea where that one comes from. It's always been there for some reason. I'm wondering if any consequences actually happen, such as the thousands of entities on one place or the erroneous chunloading.

**Comment by asiekierka** [comment] 2015-05-03 20:41
@ruifung - use http://asie.pl/FuriousCraft-0.0.18.jar - it fixes the problem by removing rapid loads/unloads and instead caching chunks which are constantly re-accessed

**Comment by Deathlymad** [comment] 2015-06-22 04:47
@Vazkii It looks like a default minecraft mnesage, it is just a guess but Minecraft might save ongoing manburst entities while shutting down. ON Restart some of the entity data is probably invalidated which results in that error. However i might be wrong since I am not sure how entety Throwable is handeled.

**Comment by Vazkii** [comment] 2015-06-28 15:40
Does this still happen in 194?

**Comment by Vazkii** [comment] 2015-07-04 16:06
Closing for lack of updates.

**Closed by Vazkii** 2015-07-04 16:06 UTC
Labels: investigate
