### ISSUE TITLE
The Terra Shatterer should be able to place torches

### ISSUE THREAD

**Issue by UntouchedWagons** [Vazkii/Botania#1018] opened 2015-05-25 00:08 UTC
The Manasteel Pickaxe is able to place vanilla torches but not the Terra Shatterer which I feel is a bit of a downgrade. The Shatterer should be able to place vanilla torches (support for TiCon's stone torches would be awesome too) via right-clicking with the ability activation be relegated to shift right clicking.

**Comment by MrKunji** [comment] 2015-05-25 00:10
The Terra Shatterer does place torchs, via shift-RC, do you want the controls to be inverted?

**Comment by UntouchedWagons** [comment] 2015-05-25 00:13
Shift right clicking activates the Shatterer's ability for me.

**Comment by MrKunji** [comment] 2015-05-25 00:15
See at version 186
http://botaniamod.net/changelog.php

**Comment by UntouchedWagons** [comment] 2015-05-25 00:16
TPPI2 has version 170. (╯°□°）╯︵ ┻━┻ Oh well.

**Comment by UntouchedWagons** [comment] 2015-05-26 02:01
I just upgraded to version 190, shift right clicking the shatterer does not place torches. It only activates or deactivates it.

**Comment by MrKunji** [comment] 2015-05-26 15:33
Ok, so I will try to reproduce.

**Comment by Lazersmoke** [comment] 2015-05-28 01:55
I can't reproduce using my custom build straight from Github, so this issue has been fixed in at least the latest github source code. Maybe check your keybindings?

**Comment by UntouchedWagons** [comment] 2015-05-28 02:01
I couldn't find any options for Botania keybinds.

**Comment by MrKunji** [comment] 2015-05-28 02:02
Because Botania doesn't have keybinds

**Comment by UntouchedWagons** [comment] 2015-05-28 02:03
No wonder I couldn't find them.

**Comment by TheWhiteWolves** [comment] 2015-05-29 11:09
@UntouchedWagons is this happening for you with only Botania installed?

**Comment by Barhandar** [comment] 2015-05-29 13:13
I'm on 189 and TS places torches just fine. Are you sure you HAVE torches in inventory?

**Comment by Vazkii** [comment] 2015-05-29 17:04
Can't reproduce.

**Closed by Vazkii** 2015-05-29 17:04 UTC
Labels: investigate, needs-info
