### ISSUE TITLE
Excalibur Crash [r1.6-173]

### ISSUE THREAD

**Issue by jawdylawdy** [Vazkii/Botania#718] opened 2015-04-03 13:29 UTC
FastCraft 1.17
Latest version of Forge
No mods other than Botania

Just fiddling around with some of the cool new stuff and swung Excalibur a few times, crashed with this error.

http://pastebin.com/JCadGtqS

**Comment by jawdylawdy** [comment] 2015-04-03 13:30
Should be noted that this crash happens whenever you swing Excalibur, no matter what.

**Comment by Vazkii** [comment] 2015-04-03 13:31
Dupe of #705

**Comment by MrKunji** [comment] 2015-04-03 13:31
Same as https://github.com/Vazkii/Botania/issues/705, it needs CodeChicken Core.

**Closed by Vazkii** 2015-04-03 13:31 UTC
