### ISSUE TITLE
Flowers un-linking from other items

### ISSUE THREAD

**Issue by Cuppycake** [Vazkii/Botania#995] opened 2015-05-20 00:20 UTC
We are having a recurring issue on one of our servers. It seems on chunk unload or server restarts all the flowers un-link from spreaders and the like. Each time the player has to hand link the flowers again and again. I thought maybe it was cauldron causing an issue but we run two servers of the same modpack with no issues on the other using the same mods, configs, and server jars.

**Comment by MrKunji** [comment] 2015-05-20 00:24
If the server isn't running with Botania v190, nothing can be done.

**Comment by Cuppycake** [comment] 2015-05-20 00:25
The server is in fact running Botania v190.

**Comment by Error998** [comment] 2015-05-20 07:23
I can confirm this behaviour of flowers unlinking randomly after a chunk unload or server reset. Unfortunately it also does not seem to always happen, but more like 90% of the time.  Pitty there is no crash or log to help with fixing this issue.

**Comment by Barhandar** [comment] 2015-05-20 16:34
Does the player have flowers and spreaders in separate chunks?

**Comment by Error998** [comment] 2015-05-20 16:57
With my setup the flowers and the spreader it's connected to is in the same chunk

**Comment by Cuppycake** [comment] 2015-05-20 19:41
Same as on our server. Doesn't seem to matter the layout or location of the setups.

**Comment by mrdeadlocked** [comment] 2015-05-21 13:49
I'm having this same issue.

**Comment by mrdeadlocked** [comment] 2015-05-23 15:25
I have hydrongeas that are having this issue. I have the same setup mirror next to it with floating hydrongeas and the 'non' floating flowers have unlinked from spreader. I have yet to have the problem with floating plants.

**Comment by ErkCurley** [comment] 2015-05-25 20:56
I have been having the issue with floating thermalilys as well as non-floating flowers such as the endoflames. I also have linked flowers that are in the same chunk as to avoid any issues there. 

The server and all the clients are running: Botania-r1.6.187

**Comment by mrdeadlocked** [comment] 2015-05-26 11:57
Yep. I had it happen with floating hydro's too. I must've just been lucky up until then. This bug is so annoying.

**Comment by Vazkii** [comment] 2015-05-29 17:50
Tired everything I could with botania and railcraft for chunkloading. Possible crossmod issue I reckon, then.

**Comment by cauliflower69** [comment] 2015-06-02 13:51
Same issue, using chicken chunks.

**Comment by mrdeadlocked** [comment] 2015-06-04 17:10
I had this issue happen with flowers that weren't chunk loaded by any mod. Just on server resetting some of the flowers didnt sync back to spreaders.

**Comment by Cuppycake** [comment] 2015-06-04 17:14
Same. We do not allow chunkloading of personal bases on our server. Seems its just on restarts but kind of hard to tell if its in fact on a full server restart or just a chunk unload.

**Comment by Vazkii** [comment] 2015-06-04 18:13
Locking to prevent more "same here" posts. If you feel you have pertinent info to submit, contact me on IRC.

**Comment by Vazkii** [comment] 2015-06-08 22:11
I tried a fix with build 192. Unlocking to allow for discussion if it did anything or not.

**Comment by TheWhiteWolves** [comment] 2015-06-10 19:52
Issue #1081 may be linked to this, but I can't be certain.

**Comment by mrdeadlocked** [comment] 2015-06-12 10:36
I just updated server with 192.Logged off for the night. Had a restart over night, logged back in this morning and flowers are unlinked from spreaders again.

**Comment by bookerthegeek** [comment] 2015-06-13 02:34
Sorry to jump in but we were having this issue on our server. It was caused by any clear lag style plugin viewing the link as an entity. (Not that is or isnt, just that is the easy way to explain it)

Once we whitelisted anything from botania from clear lag, the de-linking stopped

**Comment by mrdeadlocked** [comment] 2015-06-15 12:42
I do not have any clear lag style plugins on my server. We use the following: Betteralias, CHatEx, Craftirc, DynmapCBBridge, Essentials, essentialsprotect, essetialsspawn, minestats, offlineteleporter, pex, playtime, restartannounce, vault, worldborder, booscooldowns, prism, weather reduces, worldeditbukkit. 

Bookerthegeek- are any of these the same you used?

**Comment by cauliflower69** [comment] 2015-06-16 15:32
Does the same thing occur when not using Cauldron (kcauldron) ?

**Comment by bookerthegeek** [comment] 2015-06-16 18:14
@Mrdeadlocked

We have the essentials, world border as prism. We did have pex but have moved away from it to another permission plugin. 

Sadly the issue has come back. The clear lag issue was actually removing the manna bursts when there was not a valid target that accepts manna. As in you have a spreader pointed at a pool but then remove the pool. This caused a massive increase in lag for some reason that was solved by clearing the mana bursts with the clear lag plugin. 

After some more testing we are still having the issue of the flowers unbinding upon chunk loading/unloading. 

I will test tonight in singleplayer if the issue persists.

Chunk loading the flowers does cause them to not unlink. Server restarts do cause them to unlink.

@vazkii
would it be possible to get a server side only patch when you fix this issue? Would be more then happy to test it for you on our server, sadly as we run ftb packs we can not force our users to upgrade only this mod and keep our player base.

**Comment by Elvarion** [comment] 2015-06-18 14:38
After updating to 192 ive had less/no unbinding of flowers. However! Im now having trouble with the Redstone manaspreader. Whenever the chunk/server unloads/restarts it stop working, and I need replace it to get it working again.

Botania r1.6-192
Forge-1.7.10-10.13.3.1395-1710ls

**Comment by Nagapito** [comment] 2015-06-18 16:46
My questions is, does this error occurred to anyone in single player or a normal forge server with no plugins?

**Comment by cauliflower69** [comment] 2015-06-18 17:08
Exactly what I was wondering earlier Nagapito

**Comment by Elvarion** [comment] 2015-06-18 17:13
Im using regular Forge, So cant have plugins (Or atleast im not using plugins if that now is a thing and ive not heard about it)

Havent tried singleplayer. But could do so in a couple of hours when im back at the computer

**Comment by Nagapito** [comment] 2015-06-18 21:30
@Elvarion does your server lags a little, has some tps issues, specially on reboot?

**Comment by Elvarion** [comment] 2015-06-19 06:49
90% of the time the server is running a smooth 20tps. Most of the time when I start the server I will get a "Can't keep up! Did the system time change, or is the server overloaded?" and it will skip a few ticks. But that's about it

**Comment by Vazkii** [comment] 2015-06-20 00:14
From here on in I only accept reports based on Botania 193. You folks who had the issue, please check if it still exists in it.

**Comment by Elvarion** [comment] 2015-06-20 07:49
And we might have a Winner!
Started the Server, My manaspreader is working right of the bat. 'Awesome!'
All my flowers are working after a chunk reload / server restart 'Awesome!'

193 fixed my problems at least, Hopefully it fixes it for other people also.
I humbly thank you Vazkii!

**Comment by Nagapito** [comment] 2015-06-20 09:19
Confirm its really rebindig to the previous spreader and not just but binding to the closest one because it failed to bind to the correct one

**Comment by mrdeadlocked** [comment] 2015-06-20 16:11
Logged in after installing 193 and all of my flowers are bound to a spreader. before update 90% of my flowers were unbound. i'll post an update when I have some reboots/further testing. So far so good.

**Comment by Vazkii** [comment] 2015-06-28 15:40
You folks that have the bugs, report the status in 194 please.

**Comment by mrdeadlocked** [comment] 2015-06-28 22:15
Just updated to 194 and My flowers are all linked after some restarts/server shutdowns. I don't have any flowers linked to further away spreaders, so I dont know if they're just rebinding to closest or not.

**Comment by bookerthegeek** [comment] 2015-07-01 04:37
We have found an interesting fact f.y.i.

version: r1.6-192 is not having this issue (Cloud 9 modpack)
version: r1.6-187 is having the issue (TheDarkTrilogy)
version: r1.6-190 Is having the issue (Infinity)

The main difference we have discovered so far is the lack of chicken chunks in the packs.
I will continue to test this for you if you so wish you masterful mod maker @Vazkii

**Comment by Nagapito** [comment] 2015-07-01 08:43
That is a very interesting fact because something similar happened to me yesterday. 
Have been playing Blast Off (Botania r1.6-187) on the last few days on a server and never had any linking problems with my flowers.
yesterday, I placed a chunk loader from chicken chunks. I believe it was the first one placed in the server. After server restart, half my flowers were unlinked!

**Comment by Vazkii** [comment] 2015-07-04 16:07
If nobody reports it happening in 194 I'll call it closed.

**Comment by bookerthegeek** [comment] 2015-07-04 22:42
@Vazkii I'll test tonight and report back in the morning. 

Happy 4th of July everybody.

**Comment by bookerthegeek** [comment] 2015-07-05 20:31
Mods and versions used in testing: (All are the latest version)
* Forge 10.13.4.1448
* Baubles 1.0.1.10 
* Botania r1.6-198 
* Chicken Chunks 1.3.4.19
* CodeChickenCore 1.0.6.43
* NEI 1.0.4.107

Testing setup on a flat world test in single player: (Not in spawn chunks)
* Placed Two Cake flowers three blocks from cake to the east and west
* Place mana pool three blocks north of cake
* Placed mana spreader on top of cake and one cake flower
* Placing a chunk loader to cover the area
* Second test involed the removal of Chicken Chunks and testing in a new instance

How I teseted:
* Upon inspection with wand, both flowers are linked to spreader above cake
* Forced linked one flower to center spreader
* Traveled 1k blocks and logged out
* Logged in and traveled back

What I found:
* The flower that was forced linked stayed linked to the center spreader
* The flower that was not forced linked, changed from being linked from the center spreader to the nearest spreader
* Repeating the test with a chunk loader removed did not change the results.

Conclusion: (personal ones of course)
* Flowers when unloaded and reloaded will rebind to their destination if Manually set
* Flowers not manually set relink to the nearest spreader
* Chicken chunks does not effect this issue.

Hope this helps.

**Comment by bookerthegeek** [comment] 2015-07-05 20:42
Results are identical no matter if you are in Botania 194 or 198

* Flowers that are force linked to spreaders remain linked to those spreaders upon chunk/world reloading
* Flowers that are NOT manually linked relink to the nearest spreader upon chunk/world reloading

**Comment by Vazkii** [comment] 2015-07-20 20:05
Fixed by https://github.com/Vazkii/Botania/commit/3a078edafec782abad50f5a706cd21d162ef30f7

**Closed by Vazkii** 2015-07-20 20:05 UTC
Labels: bug, compatibility, gamebreaking
