### ISSUE TITLE
Bug report for 1.16.1

### ISSUE THREAD

**Issue by MrStatman80** [Vazkii/Botania#3419] opened 2020-08-19 06:11 UTC
I had a crash report and i sent to you and Mezz but he is blaming you for the crash as well as Optifine

I searched something in Jei and then it crashed but crash report said Botania and JEI

So i sent both of you crash reports

**Comment by Hubry** [comment] 2020-08-19 11:22
* You haven't posted a crash report link at all here
* If you looked at recent issues you wouldve seen at least 5 of similiar crash reports  

Remove Optifine, or downgrade Forge to build 106. 

Duplicate of #3387

**Closed by Hubry** 2020-08-19 11:22 UTC
