### ISSUE TITLE
Crash while rendering a Block Entity

### ISSUE THREAD

**Issue by CookieGD** [Vazkii/Botania#4257] opened 2022-12-30 22:08 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Fabric: Loader 0.14.12 API 0.70.0

### Modpack info

private Modpack

### The latest.log file

https://pastebin.com/1jDSJVsH

### Issue description

My game crashed while I was looking through the pages of the Lexica Botania and according to the crash logs it's because of some render issues most likely caused by the Manaseer Monocle.

### Other information

I play in a private fabric modpack for 1.19.2 that I'm currently working on. Not too sure, but maybe check for some connection to the [Identity](https://www.curseforge.com/minecraft/mc-mods/identity) mod as at the time I was morphed into another mob.

**Comment by williewillus** [comment] 2023-01-28 06:47
Marking this a duplicate of #4275 since that issue is the same thing and there's more crash samples in that ticket

**Closed as not planned by williewillus** 2023-01-28 06:47 UTC
