### ISSUE TITLE
Hello, there was an error on my server.

### ISSUE THREAD

**Issue by Alan-Yi** [Vazkii/Botania#2932] opened 2019-06-18 06:11 UTC
Botanical Version: Botania+r1.10-361.jar
And Baubles-1.12-1.5.2.jar
Once the player enters the server and crashes the client directly, the problem is very painful.
My mailbox is 3584468568@qq.com.
Next I upload the client error file for you
[crash-2019-06-18_13.29.46-client.txt](https://github.com/Vazkii/Botania/files/3299993/crash-2019-06-18_13.29.46-client.txt)
[crash-2019-06-18_13.36.23-client.txt](https://github.com/Vazkii/Botania/files/3299995/crash-2019-06-18_13.36.23-client.txt)

**Comment by williewillus** [comment] 2019-06-23 17:58
this is the same problem as #2205, so I will close this and move discussion over to that ticket. We think the problem is caused by voxelmap, so try replacing it with a different minimap mod.

**Closed by williewillus** 2019-06-23 17:58 UTC
