### ISSUE TITLE
[1.20.1] Please add an option to display Botania's tab on the second page of the creative inventory, instead of replacing the "Spawn Eggs" tab.

### ISSUE THREAD

**Issue by VOLKOUL** [Vazkii/Botania#4562] opened 2024-01-23 13:37 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

Botania-1.20.1-443-FORGE

### Modloader version

NeoForge 1.20.1-47.1.88

### Modpack info

Custom

### The latest.log file

https://mclo.gs/gw5Yy6H (sorry for the big modpack)

### Issue description

Botania's tab in the creative inventory replaces the "Spawn Eggs" tab. I believe this is intentional, but having an option to revert it would be great. Basically just move Botania's tab to the second/third/whateveryouwant page of the creative inventory, just like any other mod does.

### Steps to reproduce

LAUNCH GAME
JOIN WORLD
OBSERVE

**Comment by anoomolu** [comment] 2024-02-09 11:35
Seems like an issue exclusive to the Forge version of Botania. It's not supposed to replace any tabs.

On Fabric 1.20.1:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/f174a8c6-2b32-4002-914e-7de40611bbfc)

On Forge 1.20.1:
![image](https://github.com/VazkiiMods/Botania/assets/77850233/91b7dd69-8e6c-4039-994e-a376465195a1)

Forge 1.19.2 works as it should.

**Comment by VOLKOUL** [comment] 2024-02-09 12:25
Huh, I thought it was intentional. Weird...

**Comment by anoomolu** [comment] 2024-03-22 10:39
Closing as duplicate of your other issue which has a more accurate title.

**Closed as not planned by anoomolu** 2024-03-22 10:39 UTC
