### ISSUE TITLE
Tainted Blood Pendant of Vanity's Emptiness does nothing

### ISSUE THREAD

**Issue by auxiliary-character** [Vazkii/Botania#3172] opened 2020-02-10 22:08 UTC
# Version Information
Forge version: 28.2.0
Botania version: r1.11-377

# Further Information

Steps to reproduce:
1. Wear Tainted Blood Pendant
2. Walk into dark area where mobs can spawn

What I expected to happen:
Mobs prevented from spawning

What happened instead:
Mobs spawn

![2020-02-10_16 06 27](https://user-images.githubusercontent.com/860799/74194799-9c684e00-4c1f-11ea-8866-45659cd7b2df.png)

**Comment by williewillus** [comment] 2020-02-10 22:22
duplicate of #3098

**Closed by williewillus** 2020-02-10 22:22 UTC
