### ISSUE TITLE
[1.16 crash] Botania Spreading mana with mana spreader

### ISSUE THREAD

**Issue by Sebulba13** [Vazkii/Botania#3399] opened 2020-08-13 09:07 UTC
# Version Information
Forge version:  1.16.1-forge-32.0.108
Botania version:  Botania-1.16-401 (Botania-1.16-399 when bug appeared) 

# Further Information
Link: https://gist.github.com/Sebulba13/6dc42a8636e39711612e83197f100b5a
Steps to reproduce:
1. Just start producing mana with the flower

What I expected to happen: produce some mana

What happened instead: game crashing every time I'm entering the server, but server stays cool. I have a lot of different mods, but I haven't used them yet. Only "connected glass" is placed nearby.

**Comment by Hubry** [comment] 2020-08-13 10:03
Duplicate of #3397

**Closed by Hubry** 2020-08-13 10:03 UTC
