### ISSUE TITLE
Mana Pool Loading Crash

### ISSUE THREAD

**Issue by SuperSaiyanSolar** [Vazkii/Botania#1948] opened 2016-10-15 03:25 UTC
FML Log: http://pastebin.com/AbM3u7Zh
Crash Report: http://pastebin.com/Bu1pLbAR

Hey, I hope this submits... This is the link to the FML Log for a crash that a few friends and I have been having repeatedly on a private server we're hosting containing the Botania mod. It seems to have calmed down after removing the mana pools that had mana in them, but it was to the point where I literally could not join no matter what until the pools were removed. I mentioned this bug and crash report on Minecraft Forum, but I felt like getting it to you directly was a good idea considering how troublesome this bug has been. We're running the current version of Botania along with the newest Forge (not MCPC+).

(Note that this bug also occurs after dying in a chunk containing the pools, after loading in a chunk with the pools, or joining in when you logged off in a chunk with the pools. It does not occur every time, nor does it happen at the same rate to every player.)

**Comment by frank89722** [comment] 2016-10-16 10:29
I just tried it work with the beta version jounerymap, it'll crash client.
But it's work fine with the old jounery map.

**Comment by frank89722** [comment] 2016-10-16 10:34
https://bitbucket.org/TeamJM/journeymap/issues/124/53x-crashed-botania

**Comment by techbrew-mc** [comment] 2016-10-17 23:07
@frank89722 All you did in your bugreport to me was link back here with zero information about how JM is related.  If you're going to take the time to report something, report usable information please.

**Comment by Vazkii** [comment] 2016-10-19 19:32
Dupe of #1950 (I know it came after but I'm just collecting them all in there)

**Closed by Vazkii** 2016-10-19 19:32 UTC
Labels: compatibility, investigate
