### ISSUE TITLE
Sugar Cane Cannot be Planted on Vivid Grass Without Water

### ISSUE THREAD

**Issue by rehashedsalt** [Vazkii/Botania#3893] opened 2022-01-01 02:28 UTC
### Mod loader

Fabric

### Minecraft version

1.18.1

### Botania version

1.18.1-427-FABRIC

### Modloader version

Fabric: Loader 0.12.12 + API 0.45.0

### The latest.log file

https://gist.github.com/rehashedsalt/3a737798b7b84b1f703719a0c472ff74

### Issue description

On the above version of Botania, Sugar Cane cannot be placed on any form of Vivid Grass without a water source nearby. Per #1736, being able to do so was a bug-become-feature that allowed for dense and clean Sugar Cane farms (though the second half of an ideal setup is [still bugged](https://github.com/VazkiiMods/Botania/issues/3506)).

Unsure if this affects 1.17 or any earlier patches of 1.18; I merely noticed it when verifying #3506 on the latest version of Botania.

### Steps to reproduce

1. Install the things
2. Place some form of Vivid Grass without water adjacent
3. Right-click with Sugar Cane
4. Be sad

### Other information

"Modpack" used for testing is completely minimal; only other mods involved were dependencies like Trinkets and Patchouli; I doubt they're related.

**Comment by Hubry** [comment] 2022-01-26 14:16
This behavior existed because to make plants plantable on the grass at all, the grass needed to use the Forge hook for plant sustaining. This got dropped off during the port to Fabric, as the hook doesn't exist there - and Minecraft using the dirt tag for sugar cane makes it mostly obsolete.

Kinda tempted to close this as "works as intended". This would need a mixin on Fabric which isn't a big deal, but managing water around these farms isn't as much of a pain as it used to, so idk.

**Comment by rehashedsalt** [comment] 2022-01-26 17:45
Yeah, with the addition of waterlogging, sugar cane farms got much cleaner and denser in Vanilla. I wouldn't be heartbroken if this went away, but there is charm to the detail IMO. If the code is easy to write and maintain, I'd vote to keep it.

If this does get dropped, though, you may want to stuff a note in a changelog or something. That way the difference in behavior is more discoverable.

**Comment by artemisSystem** [comment] 2024-10-06 19:59
I had no idea this was even a thing. Don't think it's really worth bringing back

**Closed as not planned by artemisSystem** 2024-10-06 19:59 UTC
Labels: investigate
