### ISSUE TITLE
[1.14.4] Water is flashing brown for a split second whilst picking up items. [GIF Inside]

### ISSUE THREAD

**Issue by Gbergz** [Vazkii/Botania#3122] opened 2020-01-06 11:47 UTC
# Version Information
Forge version:  **28.1.107**
Botania version:  **r1.11-373**
MC Version: **1.14.4**

# Further Information
Steps to reproduce:
1. Pick up an item
2. Look at the water
3. See it flashing brown for a split second, as soon as the item is picked up.

**What I expected to happen:**
*No flashing water when picking up items.*

**What happened instead:**
*Brown flashing water for a split second, as soon as the item is picked up.*

## Video/GIF showing what happens:
[https://gyazo.com/4bd237823f6141b4dd361a139d36e52a](https://gyazo.com/4bd237823f6141b4dd361a139d36e52a)

# More info:
I've tried this in a modpack where i noticed it. 
And now i've gone ahead and ONLY installed Botania (1.14.4) w/ its required mods. Patchouli & Curious API. So a clean installation of Forge w/ what is noted above^ 
And it still happened.

EDITS: fixed texts

**Comment by Hubry** [comment] 2020-01-06 13:47
Duplicate of #3088, fixed in dev

**Closed by Hubry** 2020-01-06 13:47 UTC
