### ISSUE TITLE
Special grasses don't spread beyond a certain radius

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Botania#1666] opened 2015-12-17 05:08 UTC
Once they fill up the initial square, they aren't spreading any further. They also don't seem to be spreading up or down single blocks like normal grass. Using version 244.

**Comment by phantamanta44** [comment] 2015-12-17 05:24
By "special grasses", do you mean grasses spawned by grass seeds? Because this is expected behavious.

**Comment by Zsashas** [comment] 2015-12-17 05:37
I was under the impression that they would continue to spread like normal grass, and were not limited to a small area.

**Comment by JRoffel** [comment] 2015-12-17 08:00
"... An additional six types of Pasture Seeds can be created, for alternative grass types with various textures.
These spread to dirt like normal and can sustain any plant a block of grass can. Similarly, they may only be picked up with Silk Touch. However, they do not decay back into dirt if there's a block above them." --[Lexicon Botania](http://www.botaniamod.com/lexicon.php)

Unless I misunderstand either this issue, or this entry, the grass types SHOULD spread. So either the lexicon is wrong, or  there is a bug which makes it not spread

**Comment by Zsashas** [comment] 2015-12-17 08:40
It may be connected to whatever limits them to that radius when first created. Somehow, it stays limited.

**Comment by PikadudeNo1** [comment] 2015-12-17 09:00
I poked around in the code and found BlockAltGrass.java, the file apparently responsible for special grasses, and there's nothing in there that would cause such behavior; it doesn't even track the block/seed it originally came from. You sure your grass is well-lit?

**Comment by Zsashas** [comment] 2015-12-17 09:37
It's out in the open, under direct sunlight. The square of scorched grass near my nether portal hasn't spread in days. 

Actually, looking at it further, it isn't even filling in the square. After some time, it just straight up stops.
![2015-12-16_20 59 24](https://cloud.githubusercontent.com/assets/6917535/11866241/9fcda6a2-a45e-11e5-8097-e8d7a98f14a9.png)

**Comment by PikadudeNo1** [comment] 2015-12-17 09:42
It doesn't override other grass types, just like with vanilla grass & mycelium. Only the initial burst from the Pasture Seed can do that. You need plain dirt where you want it to spread.

**Comment by JRoffel** [comment] 2015-12-17 12:52
Not an issue, please close

**Comment by Zsashas** [comment] 2015-12-17 16:02
No, it won't even keep spreading on normal dirt/grass.

**Comment by JRoffel** [comment] 2015-12-17 16:05
It won't spread to grass... Dirt however? It should spread to, are you sure it's pure, vanilla dirt? Or is there a different mod that might mess with it? If so, could you also try this in just vanilla + botania

**Comment by Zsashas** [comment] 2015-12-17 16:24
It's just vanilla dirt. It was dirt there but vanilla grass spreads much faster than these types do.

**Comment by JRoffel** [comment] 2015-12-17 16:30
So it does spread to the dirt blocks, only slower than normal grass?

**Comment by Zsashas** [comment] 2015-12-17 16:37
Yes, much slower.

**Comment by JRoffel** [comment] 2015-12-17 16:59
That means this issue is not correct, could you (or someone else with that power) close this issue?

**Closed** 2015-12-17 17:18 UTC
