### ISSUE TITLE
Flügel Tiara crash

### ISSUE THREAD

**Issue by BarbasTheDog** [Vazkii/Botania#666] opened 2015-03-18 02:31 UTC
When I tried to change the appearance of the wings using a piece of green quartz, the game threw this error log and crashed:

http://pastebin.com/C2jaiQvV

**Comment by Vazkii** [comment] 2015-03-18 13:26
Dupe of #649.

**Closed by Vazkii** 2015-03-18 13:26 UTC

**Comment by Durpady** [comment] 2015-03-18 20:39
Satanic dupe?
