### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by EEENEXY** [Vazkii/Botania#4303] opened 2023-02-24 10:31 UTC
### Mod Loader

Forge

### Minecraft Version

1.19.2

### Botania version

1.19.2-437

### Modloader version

Forge 43.2.3

### Modpack info

One botany mod

### The latest.log file

-

### Issue description

When pointing the staff of the forest at the distributor, flower or pool of mana, the amount of mana in the item is not shown.

### Steps to reproduce

1. Point the staff at the object
2. There is no mana

### Other information

-

**Comment by LeoBeliik** [comment] 2023-02-24 14:16
do you have optifine? if so that's the problem.

**Comment by mintynoura** [comment] 2023-02-28 10:12
Is there no way to fix it without removing Optifine? I could've sworn the two mods worked just fine together in 1.16

**Comment by artemisSystem** [comment] 2023-03-05 09:09
Optifine broke this in 1.19. I'm pretty sure nothing changed on botania's end. Duplicate of #4258

**Closed as not planned by artemisSystem** 2023-03-05 09:09 UTC
