### ISSUE TITLE
Bore Warp tree farm removed?

### ISSUE THREAD

**Issue by LucidDreamer0322** [Vazkii/Botania#3481] opened 2020-10-11 19:11 UTC
# Version Information
Forge version:  1.16.3  34.1
Botania version:  1.16.2 406

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step: Made a bore-warp tree farm like i used to in the old days.
2. Second step: Looked up videos on how to do it because my tree farm didn't work.
3. Third step: Saw the update about mana being voided if its been warped, but that's snot an issue.
4. Fourth step: Consulted a bunch of old posts but never found the one I am having.

What I expected to happen:
things breaking, dropping, getting picked up, placed, stored ect.
What happened instead:
Nothing. Trees grow, munchdew eats the leaves, gives the spreader mana, and the spreader never fires. the only way i can get it to fire is if there is no force block between it and the mana pool.  It works if i quickly place the force block back down, so it has nothing to do with the lens or the force block, or anything. My deduction is simply that the spreader will not fire at a force block even if there's a mana pool on the other side. Is this intended behavior?

**Comment by Hubry** [comment] 2020-10-11 19:58
What is a "bore-warp tree farm like i used to in the old days"? Screenshots (or even videos) of your setup, and descriptions of a minimal reproduction case (the most barebones setup that reproduces what you are describing) would be useful, instead of reminiscing old days :P 

My assumption about what you are reporting is "Bore Warp lens placed on a Mana Spreader wont try to shoot at a Mana Pool placed behind a Force Relay".

Which I cannot reproduce: 
![Image](https://user-images.githubusercontent.com/26120076/95688727-837bc680-0c0c-11eb-9969-f859105ad55e.png)

**Comment by LucidDreamer0322** [comment] 2020-10-11 20:44
interesting, maybe a mod conflict then, i will do some screen shots and modlist when i get home :)

**Comment by LucidDreamer0322** [comment] 2020-10-12 17:40
![image](https://user-images.githubusercontent.com/25113035/95773847-43105d00-0c8d-11eb-8736-aa761058eb8f.png)
(Never uploaded a pic so I hope that works)

So:
1. Due to the update where mana pulses after warp no longer providing mana to blocks I have added a 2nd spreader under the Hopperhock pointing at the pool for the Munchdew to link to to provide mana to the system, (Working)
2. The Rannuncarpus and Hopperhock are linked to the pool and accept mana and function accordingly. (Working)
3. The bore warp spreader is set up to fire a pulse into the force block above it by being linked to the pool above that, which would warp it to the sapling blocks and up to one of the other force block and into the other accordingly, but it is (Not Working)
   - (I CAN get it to work by breaking and immediately replacing the first force block in the system, and have tried setting up a Redstone system with observers and sticky pistons to move the force block back and forth, but apparently they do not allow piston physics.)

Here is the mod list.  The mods.rar is just the mods packed up for my players to download, 95% sure that isn't an/the issue.
![image](https://user-images.githubusercontent.com/25113035/95774978-79e77280-0c8f-11eb-91ac-1ee170481f34.png)

My server pc is running an i7 and has 8Gb of ram (out of 16) allocated, and there is only 4 of us that play consistently so its not a hardware issue.  And I can't think of any line of code that would be in any of those mods that would affect the way the spreader handles it's "can/should fire", MAYBE ars nouveau or random enchants with their custom targetting/projectile code....?

**Comment by Hubry** [comment] 2020-10-12 21:36
The easiest thing to try would be removing half of the mod list and trying to reproduce it, then repeating the process until you are left with only the culprit. (You might need to make a world with just Botania and the setup and copy it every time, or rebuild it on a fresh world, due to [MC-194811](https://bugs.mojang.com/browse/MC-194811). Also some mods depend on others, keep them together.)

Also, please provide a console log if you can? Might have some clues.

**Comment by Alwinfy** [comment] 2020-10-13 00:22
May be a dupe of #3377; try replacing the pool over the Relay with a Void?

**Comment by Hubry** [comment] 2020-11-07 22:20
This might be fixed by 34dcea4dee3bb9e4c9a5f072f518a046667eaa8b now?

**Closed** 2020-11-07 22:21 UTC
Labels: cant-reproduce, needs-info
