### ISSUE TITLE
Crash when looking at page 2 of JEI with @botania in search field

### ISSUE THREAD

**Issue by coffeeordeath** [Vazkii/Botania#3402] opened 2020-08-13 17:16 UTC
# Version Information
Forge version:  forge-1.16.1-32.0.108-universal
Botania version:  Botania-1.16-399.jar

# Further Information
Link to crash log: https://pastebin.com/2F554ULX
Steps to reproduce:
1. open new world. type @Botania in the JEI search field
2. press arrow to go to second page where the mana pylon is
3. game crashes

What I expected to happen:
ability to view all recipes in JEI with @botania search tag

What happened instead:
game crashes from rendering mana pylon

**Comment by Hubry** [comment] 2020-08-13 17:31
Downgrade Forge to build 106, or remove Optifine. The current build of Optifine only guarantees compatibility with Forge 97 anyways.

Duplicate of #3387

**Closed by Hubry** 2020-08-13 17:31 UTC
