### ISSUE TITLE
Botania GOG crash between Hopperhock and Better Storage crate.

### ISSUE THREAD

**Issue by KillerRamer** [Vazkii/Botania#1718] opened 2016-01-06 19:02 UTC
http://pastebin.com/ekrmgBgy

Upon placing a Better Storage crate next to a hopperhock  I received this crash in a singleplayer world.  With the latest GOG pack with Garden of glass mod disabled.

**Comment by yrsegal** [comment] 2016-01-06 19:04
It appears to be betterstorage's fault, NOT botania.

**Comment by AEnterprise** [comment] 2016-01-07 10:34
crash is caused by better storage yes but it's crashing because botania is calling inventory methods on the client and that shouldn't heapen, all inventory code should only be executed on the server side

**Comment by Lazersmoke** [comment] 2016-01-07 18:08
I'll look up how inventories are supposed to work, and if they need to be server only I'll send a pr, but my gut tells me the betterstorage method shouldn't be throwing unchecked exceptions when it can easily recover

**Comment by AEnterprise** [comment] 2016-01-07 18:22
client side should only be rendering related, logic should be server side

also for reference: https://github.com/BCA-Team/Buildcraft-Additions/issues/460

**Comment by TheWhiteWolves** [comment] 2016-01-08 10:55
Looking at it, the crash isn't caused when we put an item into the BS crates inventory (which btw is done only on the server side, see [SubTileHopperhock.java#L115-L128](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java#L115-L128)).

Its actually before that point, the crash occurs when we test to see if an item can be inserted into an inventory (see [SubTileHopperhock.java#L95](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java#L95)).

This should just need a check adding in here to make sure this is only done on the server.

**Comment by TheWhiteWolves** [comment] 2016-01-08 21:34
Closed by bf55ee4a609c8a4cc25f9766e82685a48c6ad6c3

**Closed by TheWhiteWolves** 2016-01-08 21:34 UTC
Labels: bug, compatibility
