### ISSUE TITLE
Botania Flowers Spawn in custom dimensions

### ISSUE THREAD

**Issue by Y3Z0N** [Vazkii/Botania#3934] opened 2022-01-28 08:26 UTC
### Mod Loader

Forge

### Minecraft Version

1.16.X

### Botania version

latest

### Modloader version

36.2.20

### The latest.log file

not needed

### Issue description

it seems like botania flowers spawns in custom dimensions like
- Atum 2
- The Abyss 2
- Twilight Forest
- Blue Skies

u should probably add a config option to blacklist dimensions since botania is the only mod which causes the issue and no other mod that adds custom flowers.

### Steps to reproduce

-

**Comment by williewillus** [comment] 2022-01-28 08:32
works as intended. However, we should have a config which is tracked in #3520, so rolling this into that issue.

Duplicate of #3520

**Closed as completed by williewillus** 2022-01-28 08:32 UTC
