### ISSUE TITLE
Crash when changing soil type of floating flower

### ISSUE THREAD

**Issue by KaiserYoshi** [Vazkii/Botania#688] opened 2015-03-26 02:35 UTC
[Crash report](http://pastebin.com/aDJZjS16)

Occured when using a Boreal Seed on a floating Rannuncarpus. Same crash occurs for floating Thermalily; I assume it applies to any non-Mystical floating flower.

**Comment by Vazkii** [comment] 2015-03-26 17:59
Dupe of #686

**Closed by Vazkii** 2015-03-26 17:59 UTC
