### ISSUE TITLE
pixie spawn chance crash need help

### ISSUE THREAD

**Issue by SuddenBid** [Vazkii/Botania#4456] opened 2023-09-30 17:36 UTC
### Mod Loader

Forge

### Minecraft Version

1.16.5

### Botania version

1.16.5-420.3

### Modloader version

36.2.39

### The latest.log file

https://pastebin.com/vJbAUcLG

### Issue description

I created a World and as soon as i take damage the game crashes. It says pixie spawn chance couldnt be detected or something
Crashlog: https://pastebin.com/vJbAUcLG

### Steps to reproduce

1. Create a World
2. Search a Mob
3. Take damage from mod
4. Game crashes

### Other information

[Minecraft Modpack.zip](https://github.com/VazkiiMods/Botania/files/12775229/Minecraft.Modpack.zip)

**Comment by williewillus** [comment] 2023-09-30 18:22
Duplicate of #4445

**Closed as not planned by williewillus** 2023-09-30 18:22 UTC
