### ISSUE TITLE
Munchdew consumes Item Extraction Cable from Cyclic

### ISSUE THREAD

**Issue by theshadowake** [Vazkii/Botania#2968] opened 2019-09-10 10:06 UTC
# Version Information
Forge version:  14.23.5.2838
Botania version:  r1.10-362

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Place Munchdew
2. Place 'item extraction cable' from Cyclic in range of Munchdew.
3. Watch cable get eaten.
4. Cri Evry Tim

What I expected to happen:
Cable not be eaten.

What happened instead:
Cable was eaten.

**Comment by williewillus** [comment] 2019-09-11 19:00
Cyclic needs to not mark its cables [as leaves](https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/generating/SubTileMunchdew.java#L66)

on the other hand, this uses tags in 1.14 so it's not a bug there, but it'll be a wontfix in 1.12

**Closed by williewillus** 2019-09-11 19:00 UTC
