### ISSUE TITLE
Mana Pylons not increasing Enchanting Power for Enchantment Table

### ISSUE THREAD

**Issue by anoomolu** [Vazkii/Botania#4245] opened 2022-12-16 00:08 UTC
### Mod Loader

Quilt ~~Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)~~

### Minecraft Version

1.19.2

### Botania version

1.19.2-436

### Modloader version

Quilt Loader 0.17.8 / QFAPI 4.0.0-beta.24

### The latest.log file

https://mclo.gs/N5l3KMs

### Issue description

![image](https://user-images.githubusercontent.com/77850233/207991725-3cbae00f-2366-4438-9e5d-cf4938df3df8.png)

With the above setup (mana pylon gap enchantment table gap mana pylon), the highest level enchant is that of an unboosted enchantment table. The lexicon says two pylons should make enchants go up to level 30, which is is the case on forge and fabric, but not quilt for some reason.

Enchanting with bookshelves works fine on quilt, however.

### Steps to reproduce

Place two mana pylons with a three block gap between them, and an enchantment in the middle. Try and enchant something, should see the above result.

**Comment by artemisSystem** [comment] 2022-12-17 21:22
We might be using a somewhat naughty mixin here. Will investigate when i have time.

cc @williewillus, should we have quilt as part of the dropdown options for mod loader?

**Comment by williewillus** [comment] 2022-12-21 19:10
Does it happen in Fabric?

Re a dropdown option, we are currently targeting only Fabric officially, Quilt is just along for the ride, so probably not.

cc @MoriyaShiine who did the fix for this mixin for 1.19, in case you spot something

**Comment by artemisSystem** [comment] 2022-12-21 19:19
I bet the problem is just that it mixins to fabric code, which quilt does not support. I think quilt has an REA for this, but fabric might have an official, non-mixin way to do it too

**Comment by MoriyaShiine** [comment] 2022-12-21 22:32
Looks like it only happens on quilt. First is fabric, second is quilt, both with just (quilted) fabric api, botania, and dependencies

![2022-12-21_16 31 35](https://user-images.githubusercontent.com/45156123/209015100-d898e8ff-e741-45be-9e23-b115e2adde05.png)
![2022-12-21_16 31 36](https://user-images.githubusercontent.com/45156123/209015130-1a91b36b-1df7-4948-a29c-498d783c2901.png)

**Comment by MoriyaShiine** [comment] 2022-12-21 22:39
Using Quilt Loader with regular Fabric API works fine, so it's specifically with Quilted Fabric API (or QSL)

**Comment by MoriyaShiine** [comment] 2022-12-21 22:41
Found the offending mixin https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19.3/library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/EnchantmentScreenHandlerMixin.java

This could *technically* be fixed by adding `BlockContentRegistries.ENCHANTING_BOOSTER.put(MANA_PYLON, 15)` etc in the mod initializer if QSL is loaded but I dunno how feasible that is

**Comment by queenofthebees** [comment] 2023-01-10 21:21
it can also be fixed using just a data pack. if I'm understanding how they work correctly, that should also work perfectly fine when eg. quilt isn't installed. ya just need a file `data/quilt/attachments/minecraft/block/enchanting_boosters.json` containing `{ "replace": false, "values": { "botania:mana_pylon": 7.5 } }` & it'll load mana pylons to behave as 7.5 bookshelves/15 enchanting power.

just tested adding a data pack w just that file and a pack.mcmeta, and it fixed the issue for me

**Comment by artemisSystem** [comment] 2023-01-10 21:34
Yeah, this is what i'm planning on doing if i don't find another solution

**Closed as completed** 2023-01-29 16:14 UTC
