### ISSUE TITLE
1.12.2 Game crash, with latest Forge and Botania

### ISSUE THREAD

**Issue by RisingInIris2017** [Vazkii/Botania#2959] opened 2019-08-25 12:39 UTC
# Version Information
Forge version: 1.12.2 - 14.23.5.2838  
Botania version:  Botania r1.10-361

# Further Information
Link to crash log: https://paste.dimdev.org/axafepekag.mccrash
This is a multiplayer game crash.
Steps to reproduce:
1. First step, teleport to a certain point.
2. Second step, game crashed.
3. Some player login at that point, his game crashed too.

**Comment by williewillus** [comment] 2019-08-25 23:02
duplicate of #2205

voxelmap has identified as a likely culprit

**Closed by williewillus** 2019-08-25 23:02 UTC
