### ISSUE TITLE
Mixin Crash with Enhanced Celestials

### ISSUE THREAD

**Issue by Mysticpasta1** [Vazkii/Botania#4728] opened 2024-07-23 23:33 UTC
### Mod Loader

Forge

### Minecraft Version

1.20.1

### Botania version

1.20.1-4445-FORGE

### Modloader version

Forge 47.3.5

### The latest.log file

https://gist.github.com/Mysticpasta1/b725c60d23bcec419916e45c438d13cd

### Issue description

it crash on startup on the game

### Steps to reproduce

Install enhanced celestials and botania in the same instance and it breaks when starting it up

### Other information

https://gist.github.com/Mysticpasta1/b725c60d23bcec419916e45c438d13cd

**Comment by TheRealWormbo** [comment] 2024-07-24 05:20
Duplicate of #4607, which is already fixed and will be released in the near future.

**Closed as completed by TheRealWormbo** 2024-07-24 05:20 UTC
