### ISSUE TITLE
[1.16.5] Botania Natural_Pylon rendering item crash

### ISSUE THREAD

**Issue by Coryy82** [Vazkii/Botania#3704] opened 2021-04-10 11:19 UTC
# Version Information
Forge version: 1.16.5-forge-36.1.0  
Botania version: Botania-1.16.4-414

# Further Information
Link to crash log: https://gist.github.com/Coryy82/f0c26a7ddbaa392c352678770d031b12
Steps to reproduce:
1. Start Minecraft World
2. Open Inventory (Creative)
3. Search for Natural pylon

What I expected to happen: The item appears

What happened instead: Crash

**Comment by Hubry** [comment] 2021-04-10 11:32
Duplicate of #3647
Use a HotSpot JVM instead of OpenJ9.

**Closed by Hubry** 2021-04-10 11:32 UTC
