### ISSUE TITLE
[1.11.2] Crash on launch

### ISSUE THREAD

**Issue by vrork** [Vazkii/Botania#2335] opened 2017-08-19 15:07 UTC
Crash on launch: 
" net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania (botania)
Caused by: java.lang.NoSuchFieldError: CAPABILITY_ITEM_BAUBLE "

https://pastebin.com/33vcNxeL

**Comment by Hubry** [comment] 2017-08-19 15:48
Duplicate of #2324.

**Closed** 2017-08-20 15:24 UTC
