### ISSUE TITLE
Crashed upon searching "magnet"

### ISSUE THREAD

**Issue by RealSonarX** [Vazkii/Botania#4695] opened 2024-06-29 15:33 UTC
### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Botania version

1.20.1-444

### Modloader version

Fabric API 0.92.2 / Fabric Loader 0.15.11

### Modpack info

Custom

### The latest.log file

https://mclo.gs/VY0WFCd

### Issue description

Crashed when trying to search for "magnet" in the creative menu and looked through the logs and saw some botania name ids mentioned so figured it was related

### Steps to reproduce

1) Open creative menu
2) Search "magnet"

**Comment by anoomolu** [comment] 2024-06-29 15:43
Are you able to reproduce this with just Botania + dependencies?

**Comment by TheRealWormbo** [comment] 2024-06-29 19:50
Funny timing, I merged PR #4693 earlier today, which fixes exactly that issue. The cause of your crash is an outdated piece of Malum compatibility code in Botania. The two mods will not work together until the next Botania release.

**Closed as completed by TheRealWormbo** 2024-06-29 19:50 UTC
