### ISSUE TITLE
Thorn Chakram Crash

### ISSUE THREAD

**Issue by Zacharais** [Vazkii/Botania#2131] opened 2017-01-12 10:40 UTC
I attempted to throw the thorn chakram, at which point the game crashed. The issue also occurs with the flare chakram. This is on Botania 339, on Skyfactory 3.

Pastebin: http://pastebin.com/HAkc5jgZ

**Comment by williewillus** [comment] 2017-01-14 22:26
dupe of #2114
no one knows what's happening but some mod somewhere is messing stuff up >_<
if you could reduce it to just a few mods that still reproduce the crash that would be great

**Closed by williewillus** 2017-01-14 22:26 UTC
