### ISSUE TITLE
1.16.5 crash while browsing Botania Items on JEI

### ISSUE THREAD

**Issue by Biviho** [Vazkii/Botania#3703] opened 2021-04-07 23:46 UTC
# Version Information
Forge version:  36.1.4
Botania version:  1.16.3-1.2.10

# Further Information
from the log it looks like it's a NullPointerException while rendering one of the Pylon on JEI
Link to crash log: https://pastebin.com/DTiFrbm9

Steps to reproduce:
1. Browse item on JEI
2. reach botania
3. crash

What I expected to happen:
been able to browse items without crashing

What happened instead:
crashed

**Comment by williewillus** [comment] 2021-04-08 00:05
get rid of optifine

**Comment by Biviho** [comment] 2021-04-08 01:58
... first modpack on 1.16.5 from 1.12, i forgot to tweak optifine...
will test more tomorrow and let you know

**Comment by Hubry** [comment] 2021-04-08 09:51
No Willie, this is the OpenJ9 crash.

Duplicate of #3647, use HotSpot.

**Closed by Hubry** 2021-04-08 09:51 UTC
