### ISSUE TITLE
[1.14] Petal Apothecary discoloration

### ISSUE THREAD

**Issue by thenewdreamer** [Vazkii/Botania#2970] opened 2019-09-14 17:24 UTC
Forge version: 28.1.0
Botania version: 41.10-363-beta1  

Apothecary water turns white/gray when items are inside
![2019-09-14_13 12 24](https://user-images.githubusercontent.com/45403659/64911675-d6760800-d6f2-11e9-94c6-8c5de4447097.png)

**Comment by iTitus** [comment] 2019-10-16 16:22
Cannot reproduce in newest dev version. Probably fixed in one of the commits since last month.
![2019-10-16_18 19 16](https://user-images.githubusercontent.com/5154317/66938459-7cde6180-f041-11e9-8cc1-fda6f3dbf146.png)

**Comment by williewillus** [comment] 2019-10-16 16:42
try in another biome with brighter water, I was still running into it this week

**Comment by williewillus** [comment] 2019-10-16 16:45
Yeah just got it to happen again. It seems to depend on the angle I view the apothecary at

**Comment by iTitus** [comment] 2019-10-16 20:36
I'll try to find a desert then.

**Comment by iTitus** [comment] 2019-10-16 20:57
This seems to be a finicky one.
Still no luck
![image](https://user-images.githubusercontent.com/5154317/66958298-29cbd500-f068-11e9-8bb7-893c361161ec.png)

**Comment by williewillus** [comment] 2020-02-21 03:06
seems to not happen anymore?

**Closed by williewillus** 2020-02-21 03:06 UTC
