### ISSUE TITLE
Mana Spreader Sound issue

### ISSUE THREAD

**Issue by NEstoll** [Vazkii/Botania#4428] opened 2023-07-26 23:26 UTC
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.20.1

### Botania version

1.20.1-441

### Modloader version

Forge: 47.1.0 Fabric Loader: 0.14.21 API: 0.83.1+1.20.1

### Modpack info

N/A

### The latest.log file

N/A

### Issue description

Mana Spreaders (all tiers) do not make audible noise, yet when fired with sufficient frequency (2 spreaders firing into adjacent mana voids is enough) will cause all other sounds to become muted as well. This is likely due to the creation of too many sound events, exceeding the cap (~247 IIRC).

### Steps to reproduce

Create a world with Botania and its dependencies. Place a guilty mana pool, with 2 adjacent mana spreaders of any tier firing directly into adjacent mana voids. Wait 10-30 seconds. Observe that all game sounds are now muted, including menu sounds. Changing sound settings will temporarily restore sounds.

**Comment by anoomolu** [comment] 2023-10-05 09:02
I'm unable to reproduce this. Mana spreaders produce a "whoosh" (?) kinda sound when firing, and create around 12 sound events at max firing rate (e.g. when firing into an adjacent mana void with a velocity lens). You'd need at least 20 of these modules to get close to the sound cap, which is unlikely since the use of better spreaders and potency/velocity lenses are encouraged.

**Comment by anoomolu** [comment] 2023-11-23 00:15
May help to record this happening in a test instance, closing this for now due to inability to reproduce issue.

**Closed as not planned by anoomolu** 2023-11-23 00:15 UTC
