### ISSUE TITLE
Rendering Overlay error

### ISSUE THREAD

**Issue by NomadicVoyager** [Vazkii/Botania#4390] opened 2023-05-31 02:21 UTC
### Mod Loader

Forge

### Minecraft Version

1.19

### Botania version

 Botania-1.19.2-438-FORGE.jar

### Modloader version

Forge 43.2.8

### Modpack info

https://drive.google.com/drive/folders/1gBvrlTpVIIVNgJAcXt6xwTieTZalLmVJ?usp=drive_link

### The latest.log file

https://gist.github.com/NomadicVoyager/7df851437648c8c67ba6495b3a6bb991

### Issue description

Game Crashes

### Steps to reproduce

Crash on Loading Game

### Other information

[crash-2023-05-31_14.05.17-client.txt](https://github.com/VazkiiMods/Botania/files/11607835/crash-2023-05-31_14.05.17-client.txt)
https://bytebin.lucko.me/ztVwPuOB5B

**Comment by williewillus** [comment] 2023-06-03 04:56
Duplicate of #4345

**Closed as not planned by williewillus** 2023-06-03 04:56 UTC
