### ISSUE TITLE
Ticking Botania Entity Error on Heavily Modded Server

### ISSUE THREAD

**Issue by Eogen** [Vazkii/Botania#2731] opened 2018-09-04 02:43 UTC
# Version Information
Minecraft: minecraft_server.1.12.2.jar
Forge version:  forge-1.12.2-14.23.4.2759-universal.jar
Botania version:  Botania+r1.10-356.jar

# Further Information
Link to crash log: [http://www.knodel.net/technic/CrashDumpLogs/Botania/crash-2018-09-03_22.34.12-client.txt](http://www.knodel.net/technic/CrashDumpLogs/Botania/crash-2018-09-03_22.34.12-client.txt
)
Other Crashlogs at [http://www.knodel.net/technic/CrashDumpLogs/Botania](http://www.knodel.net/technic/CrashDumpLogs/Botania)

Console Log of Client when trying to connect: 
```
[B#360]  [22:34:12] [main/FATAL] [minecraft/Minecraft]: Reported exception thrown!
[B#360]  net.minecraft.util.ReportedException: Ticking block entity
[B#360]  	at net.minecraft.world.World.updateEntities(World.java:1848) ~[amu.class:?]
...
[B#360]  Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.PoolVariant, values=[DEFAULT, CREATIVE, DILUTED, FABULOUS]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
[B#360]  	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201) ~[awu$a.class:?]
[B#360]  	at vazkii.botania.common.block.tile.mana.TilePool.update(TilePool.java:252) ~[TilePool.class:?]
[B#360]  	at net.minecraft.world.World.redirect$tileEntityUpdate$zbb000(World.java:4128) ~[amu.class:?]
[B#360]  	at net.minecraft.world.World.updateEntities(World.java:1832) ~[amu.class:?]
```

No errors on Server console, just normal connect info, then lost connection message.

**Comment by williewillus** [comment] 2018-09-04 05:04
Duplicate of #2205
From the discussion on that issue, it looks like voxelmap might be causing issues. Try seeing if it happens without that.

**Closed by williewillus** 2018-09-04 05:04 UTC
